### ISSUE TITLE
Another bootstrap challenge

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#103]
Dataset sent by user in Rwanda.  Study area with two strata and few detections.  Most of code below is munging data to make it as standard as possible.  As sent, strata contain no "Area" field, produces following error inside `bootit`
```
Error in indN$rate[1:nN] : only 0's may be mixed with negative subscripts 
```
because the variable `nN` takes on the value -1 [here](https://github.com/DistanceDevelopment/Distance/blob/c76c26786f41016d1222ea9ee766d72e39e44237/R/bootdht_bootit.R#L62)

If I invent a value for the "Area" field, a different error occurs
```
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column 
```
coming from [this line](https://github.com/DistanceDevelopment/Distance/blob/c76c26786f41016d1222ea9ee766d72e39e44237/R/bootdht_bootit.R#L52) within `bootit`

### Minimum reproducible example
```
deo <- read.csv("C:/Users/erexs/Documents/My Distance Projects/Deo/gishwati.csv")
deo$Region.Label <- deo$habitat
deo$Sample.Label <- deo$transect
deo$Effort <- deo$transect.length..m. * 3  # three walks of each transect
deo$distance <- deo$perp_distance..m.
deo$size <- deo$group.size

deo$habitat <- NULL
deo$transect <- NULL
deo$transect.length..m. <- NULL
deo$perp_distance..m. <- NULL
deo$group.size <- NULL
deo$date <- NULL
deo$time <- NULL

deo[-c(1,3,4,5,6)] <- lapply(deo[-c(1,3,4,5,6)], gsub, pattern = " ", replacement = "", fixed = TRUE)

deo$Area <- 62

deo.chimp <- subset(deo, species=="Chimpanzee nests")
#  re-insert rows for transects 1, 11, 17, 31, 33
#     on which chimps were not detected
fixit <- rbind(deo.chimp, deo[1,])  # T1
fixit <- rbind(fixit, deo[61, ])    #T11
fixit <- rbind(fixit, deo[105,])    #T17
fixit <- rbind(fixit, deo[127,])    #T31
fixit <- rbind(fixit, deo[130,])    #T33
fixit$distance[fixit$Sample.Label=="T11"] <- NA  # detection of other spp. on T11
fixit$size[fixit$Sample.Label=="T11"] <- NA  # detection of other spp. on T11
fixit <- fixit[-6, ]  # no detects on second visit, record not needed
library(Distance)
conunit <- convert_units("meter", "meter", "hectare")
hnhab <- ds(fixit, key="hn", truncation=20, formula=~Region.Label, 
            convert.units = conunit)
simple <- function(ests, fit) {
  return(data.frame(Label = ests$individuals$N$Label, 
                    Dhat = ests$individuals$D$Estimate))
}

out <- bootdht(hnhab, fixit, nboot=20, convert.units = conunit, 
               summary_fun = simple)
```

Data in CSV form:
[gishwati.csv](https://github.com/DistanceDevelopment/Distance/files/7019632/gishwati.csv)

#### `devtools::session_info()`
```
Distance    * 1.0.4      2021-08-17 [1] Github (DistanceDevelopment/Distance@c76c267)
mrds        * 2.2.5.9000 2021-08-17 [1] Github (DistanceDevelopment/mrds@b72b690)  
```

**Comment by erex** [comment]
Hypothesis about this issue

chimp nest data above contained nests in groups, hence a column `size`

`minke` sample data set can readily be bootstrapped
however `ClusterExercise` (same data set except a group size column is added) fails:

```
library(Distance)
data("ClusterExercise")
with.size <- ds(ClusterExercise, key="hn", truncation=1.5, formula=~size)
boot.with.size <- bootdht(with.size, ClusterExercise, nboot=5)

 Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column 
```

**Comment by dill** [comment]
I think the latter issue (due to incorrect merge labels) is fixed.

The former (lack of `Area`) column is tricky, looking into that now.

**Comment by dill** [comment]
The issue is that it's totally fine to have no `Area` column when fitting a `ds` model, so that should cause no issues when fitting a model in `bootdht`. I've revised the code to reflect this.

One tweak to your code above @erex in the situation where there is no `Area` column is to use consistent `D` results (rather than a mix of `N` and `D`) in your summary function:

```r
simple <- function(ests, fit) {
  return(data.frame(Label = ests$individuals$D$Label, 
                    Dhat = ests$individuals$D$Estimate))
}
```

else things can go awry.

**Comment by erex** [comment]
thanks Dave, schoolboy error on my part.  sorry.🙇‍♂️
