### ISSUE TITLE
Incorrect binning of distances on cutpoint boundaries

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/Distance#108]
I think that `Distance`/`mrds` may not be converting exact data into intervals correctly - the issue being with values on cutpoint boundaries.  `Distance 1.0.4.9002`, `mrds 2.2.5.9000`, `R 4.1.1`.

Example code:
```{r}
library(Distance)
data("wren_snapshot")
bin.cutpoints.100m <- bin.cutpoints <- c(0, 10, 20, 30, 40, 60, 80, 100)
conversion.factor <- convert_units("meter", NULL, "hectare")
wrensnap.hn.t100 <- ds(data=wren_snapshot, key="hn", adjustment=NULL, 
                       transect="point", cutpoints=bin.cutpoints.100m,
                       convert.units=conversion.factor)
gof_ds(wrensnap.hn.t100)
```

Gives:
```{r}
Goodness of fit results for ddf object

Chi-square tests
            [0,10]  (10,20]   (20,30]    (30,40]   (40,60]     (60,80]   (80,100]     Total
Observed  0.000000 2.000000  6.000000 12.0000000 50.000000 31.00000000 15.0000000 116.00000
Expected  2.177107 6.507764 10.648053 14.1791486 33.782471 30.17006290 18.5353934 116.00000
Chisquare 2.177107 3.122414  2.028953  0.3349065  7.785346  0.02283043  0.6743319  16.14589

P = 0.0028295 with 4 degrees of freedom
```

Note that, for example, the observed count in the interval (10,20] is given as 2.

Distance for Windows gives this as 3:

![image](https://user-images.githubusercontent.com/129519/136263950-6045b81d-16e8-4ba1-bc37-656c46e973f8.png)

When I check using base `R` code, I see that 3 is correct:

```{r}
x <- wren_snapshot$distance[!is.na(wren_snapshot$distance)]
sum(x>10 & x<=20)
```
Gives 3, not 2.

I think the issue is that there is one value exactly equal to 20

```{r}
sum(x==20)
```

Gives 1.

So I think the problem is the way the software handles open and closed intervals.

**Comment by dill** [comment]
This an issue in the binning in `Distance::create.bins` (rather than anything in `mrds` or gof testing), as the data are not correct:

```r
> table(paste0(wrensnap.hn.t100$ddf$data$distbegin, "-", wrensnap.hn.t100$ddf$da
ta$distend))

 10-20  20-30  30-40  40-60  60-80 80-100 
     2      6     12     50     31     15 
```

(matching the gof output, not Distance for Windows).
