### ISSUE TITLE
Documentation for ds function says cos is recommended adjustment

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/Distance#114]
Documentation for ds function, for the adjustment argument says `adjustment terms to use; "cos" gives cosine (default), "herm" gives Hermite polynomial and "poly" gives simple polynomial. "cos" is recommended. A value of NULL indicates that no adjustments are to be fitted.`  In our workshops, we suggest pairing uniform with cosine, hazard rate with poly and half normal with herm or with cos.  Given this, it might be better to delete the sentence `"cos" is recommended`.  However, I hesitate to do so directly in the code base as there may be some numerical reason why cos is better generally.  Hence I'm raising as an issue for discussion at some point before next release.

**Comment by dill** [comment]
I don't remember why this is in there, so happy to change.
