### ISSUE TITLE
Problems specifying adjustment terms with order argument

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/Distance#115]
I'm afraid this might be a few related issues bundled together.

First, there seems to be no way to specify Hemite or simple polynomial adjustments of order 2 or 6, because error checking prevents `order=` to be followed by an even number.  (The number specified is then multiplied by 2 to produce the actual order.)

```
library(Distance)
data(book.tee.data)
tee.data <- subset(book.tee.data$book.tee.dataframe, observer == 1)
#This line works as advertised in the help - produces fit with 
# poly adjustments of order 2 and 4
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "poly", order = 2)
#This line gives an error that adjustment orders must be even for
# simple polynomials -- seemingly no way to ask for a fit with
# poly adjustments of order 2
ds.model <- ds(tee.data, trunc = 4, key = "hr", adj = "poly", order = 1)
```

Second, my reading of section 2.4 of Buckland et al. (2001) is that simple or Hermite polynomials of order 2 should only be allowed for uniform key function.  For half-normal and hazard-rate, the order should start at 4.  This is confirmed (partially) by looking at how DistWin does automated model selection.  I think this means that the `term.min` mentioned in the help for the `ds` function should be 2 for half-normal and hazard-rate.

Fixing the above issue will change the way the `ds` package does automated model selection for polynomial adjustments, so is a fairly major change.  The first polynomial adjustment tried will then be of order 4, and the next will be a model with orders 4, 6 and then 4, 6, 8 (currently the sequence is 2 then 2, 4 then 2, 4, 6...).  However, I think what is there at present is sub-optimal (and not what DistWin does).

Third, I think the documentation under `order` is a bit unclear (to me) as `term.min` is not really defined, and the whole of Buckland et al book is referred to rather than say just the section or page.  Is `term.min` supposed to be an argument, perhaps (like `max.adjustments`)?  I'm going to assume not and give the following suggested text:

order

orders of the adjustment terms to fit (as a vector/scalar), the default value (`NULL`) will select via AIC up to `max.adjustments` adjustments. The smallest allowable value is set by an internal variable `term.min` which is 1 for a uniform key and 2 for half-normal and hazard-rate keys.  If a single number is given, that number is expanded to be `seq(term.min, order, by=1)`.  Note that, for simple and Hermite polynomial adjustments, the order specified will be multiplied by 2 - see Buckland et al., 2001, Section 2.4.

**Comment by lenthomas** [comment]
In discussion, I think we have agreed that:

First, the `term.min` discussed in the help will be 1 for uniform key function and 2 for hazard-rate and half-normal key functions.  The lowest `order=` allowed when a uniform key function is used will be 1 and when half-normal and hazard-rate is used will be 2. Given this, the `seq(term.min, order, by=1)` will work as it should.

Second, there will be a new argument introduced into the function, called something like `nadj` (for number of adjustments) where the user can specify the number of adjustment terms required.  If both `nadj` and `order` are specified then `nadj` will be ignored.  Setting `nadj` is equivalent to setting `order=term.min+nadj-1`.

Third, the documentation for `order` will be updated along the lines suggested in my previous post, and documentation for `nadj` will be added.  We also need to make sure to highlight the change to users as number 1, above, will change the way some existing code works.

**Comment by erex** [comment]
Most vignettes and introductory workshop exercises do not specify what type of adjustments to use.  The only existing exercises where this occurs is the CTDS workshop using R (practical 4 on model selection).  Those exercises are not currently publicly available.

**Comment by lenthomas** [comment]
Thanks for checking.  Although it's good news that we don't need to change the instructions in our vignettes or examples, it is the case that the issue I've uncovered with term.min will affect automated model selection as well as manual.  At present, in automated model selection, for half-normal and hazard-rate key functions, `ds` incorrectly starts the sequential search with the equivalent in the above terminology with `order=1` when it should start with `order=2`.  To clarify this, I'll start a separate issue about this, and then come back and link it from here.

**Comment by lenthomas** [comment]
OK, having thought this over some more, I propose the following: (1) we introduce the `nadj` argument for specifying the number of adjustment terms and letting the software figure out which orders are appropriate, (2) we revert to referring to the "order" of adjustement term in the same way as Distance for Windows and the Buckland (2001) book does (i.e., not using j as currently, but the actual order, so for example a poly(4) is referred to as order 4), (3) we change the way the `order` argument works so it is used to manually specify the orders required.

Here is suggested help for these two:

`nadj`

the number of adjustment terms to fit. The default value (`NULL`) will select via AIC (using a sequential forward selection algorithm) up to `max.adjustment` adjustments (unless `order` is specified).  A non-negative integer value will cause the specified number of adjustments to be fitted.  The order of adjustment terms used will depend on the `key` and `adjustment`.  For `key="unif"`, adjustments of order 1, 2, 3, ... are fitted when `adjustment = "cos"` and order 2, 4, 6, ... otherwise.  For `key="hn"` or `"hr"` adjustments of order 2, 3, 4, ... are fitted when `adjustment = "cos"` and order 4, 6, 8, ... otherwise.  See Buckland et al. (2001, p. 47) for details.

`order`

order of adjustment terms to fit.  The default value (`NULL`) results in `ds` choosing the orders to use - see `nadj`.  Otherwise a scalar positive integer value can be used to fit a single adjustment term of the specified order, and a vector of positive integers to fit multiple adjustment terms of the specified orders.  For simple and Hermite polynomial adjustments, only even orders are allowed.  The number of adjustment terms specified here must match `nadj` (or `nadj` can be the default NULL value).
