### ISSUE TITLE
Error when using debug_level in ds

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/Distance#136]
The following code produces a "failure to converge" warning:

```{r}
library(Distance)
data("PTExercise")
conversion.factor <- convert_units("meter", NULL, "hectare")
bin.cutpoints.20m <- seq(0, 20, by = 2.5)
PTExercise.uf.cos.t20m <- ds(data=PTExercise, transect="point", key="unif", adjustment="cos",
                             convert_units=conversion.factor, cutpoints=bin.cutpoints.20m)
```
<img width="601" alt="Screenshot 2022-10-10 001525" src="https://user-images.githubusercontent.com/129519/194784024-d659f5c7-44f8-48ba-9429-f4307a295dc1.png">

To try to investigate the problem (I wanted to see what start values were used in the cosine(1,2) model), I tried setting `debug_level` to 1.  
```{r}
PTExercise.uf.cos.t20m <- ds(data=PTExercise, transect="point", key="unif", adjustment="cos",
                             convert_units=conversion.factor, cutpoints=bin.cutpoints.20m,
                             debug_level = 1)
```

But this led to some errors that I did not encounter without setting `debug_level`, starting with an `error in round` error:

<img width="600" alt="Screenshot 2022-10-10 001802" src="https://user-images.githubusercontent.com/129519/194784090-bce8867a-a5ab-443b-ab9e-b93a87f6c563.png">

**Comment by dill** [comment]
Closed via [0640c00](https://github.com/DistanceDevelopment/mrds/commit/0640c00494968dd3a26c9e04146f6d75fc8e91f6).
