### ISSUE TITLE
 Switch to P2 default encounter rate variance for point transects

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#138]
To match Distance for Windows, per changes from Fewster et al (2009).

Reference #135

**Comment by LHMarshall** [comment]
Loading Distance loads mrds and displays the message so separate message not required for Distance

<img width="443" alt="image" src="https://github.com/DistanceDevelopment/Distance/assets/1295691/cfcf644c-fbba-4775-8f3d-e83a707e141f">
