### ISSUE TITLE
Bug in scale coefficient estimate

### ISSUE THREAD

**Issue by rittertim** [DistanceDevelopment/Distance#14]
Dear Laura, dear all, 
I think that I found a bug in the R-Package ‘Distance’: The estimates of the scale coefficient sigma obtained by this package differ significantly from those obtained by Distance for Windows 6.2 .

I attached a small data-set (in  R-Package ‘Distance’ "flat-format", and in Distance for Windows standard format), and the distance project as well as the R-script used to analyse this data-set.

For simplicity, I used a half-normal model without adjustment-terms. I estimated the scale parameter with DISTANCE for Windows and with the R-Package ‘Distance’, and came to very different results (13.22 vs. 2.58). I also checked for the hazard-rate function (not included in the example), and got very different results again.
Suprisingly, the estimated detection rates are identical between both programms. Furthermore, the plot(ds) function offered by the R-Package obviously uses the same coefficients as estimated by Distance for Windows, and not those obtained by the package itself. This becomes obvoius when manually adding the estimated detection functions to the plot by the curve() command in R.

[distance_coeff_estimate.zip](https://github.com/DistanceDevelopment/Distance/files/660625/distance_coeff_estimate.zip)

Best, 
Tim

--
Dr. Tim Ritter
Senior Scientist
  
University of Natural Resources and Life Sciences
Institute of Forest Growth
Peter-Jordan-Str. 82
Vienna, 1190 
AUSTRIA

**Comment by erex** [comment]
Tim
Thanks for your continued vigilance regarding the distance software--you were the one who found the error in our standard error calcuations for point transects.

In this case, the R package Distance, specifically the function ds() is calling a function ddf() from the mrds package.  That function performs its parameter estimation on the log scale.  Hence, exp(2.58)=13.20.  So the estimates are similar and the detection functions (hence inferences of population size) are similar for the two pieces of software.

**Comment by rittertim** [comment]
Dear Eric, 
thanks for the ultra-fast reply. 
Obviously, it was no bug, but me not carefully reading the documentation - sorry for that.  

Best, 
Tim
