### ISSUE TITLE
alpha for confidence intervals in summary.dsmodel

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#15]
Probably the fault of `summary.ds()`, but there is no argument to permit specification of an alpha-level for the confidence intervals produced by `summary.dsmodel()`, nor is there an indication in the output of the value of alpha that is used to produce the intervals shown.

Noted by a student Anna Shaw in MT5751.

**Comment by dill** [comment]
Thanks to Anna for pointing this out!

You mean confidence intervals for the abundance/density estimates here?

**Comment by erex** [comment]
yep.

Also, found that two students were working with old versions of the 
Distance package 0.9.3 and getting that "can't cope with missing 
distances when doing truncation" error that you purged about 2 summers 
ago.

I told these students to update their R packages, but for reasons 
unknown, Distance was not detected as having an update.  I know CRAN 
shows 0.9.6 as most recent.  I don't know what repo their R-Studio was 
pointing at.

Have fun this afternoon in the "Tall Corn" state.

Eric Rexstad
20 West Braes Crescent
Crail Fife KY10 3SY



------ Original Message ------

**Comment by dill** [comment]
CIs for the density/abundance estimates from dht are an issue as they 
are calculated during the estimation phase (i.e., during the dht() call 
nested in the ds() call) not the summary() call so would have to be 
supplied to the ds() call, which seems a bit goofy.

That being said, there should be an explanation of what they are. On my 
todo list for the near future.

**Comment by erex** [comment]
From my quick scan of the code, it looked link it would not be an easy fix.  But not high on the priority list.

**Comment by dill** [comment]
I think this is a tricky one to deal with at the `summary` phase (see above) and to some extent this is addressed in `dht2` (i.e., you *can* specify a way to get the CI you want once you've fitted the model).
