### ISSUE TITLE
Error for ds models with covariates and adjustments

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#156]
If user attempts to fit a model with covariates and adjustments specified, this message is returned (using amakihi)

```
mas_adj <- ds(amakihi, transect = "point", key="hn", adjustment = "cos", formula=~MAS, truncation = 82.5) 
Model contains covariate term(s): no adjustment terms will be included. 
Fitting half-normal key function 
Error in covar_fields[i] <- colnames(data)[index] :    replacement has length zero 
AIC= 10826.537
```
This is the expected behaviour.

However, if the number of adjustment terms **is** specified, a model with both covariates and adjustment terms it fitted:

```
> mas <- ds(amakihi, transect = "point", key="hn", adjustment = "cos", formula=~MAS, truncation = 82.5, nadj=1)
Fitting half-normal key function with cosine(2) adjustments
Error in covar_fields[i] <- colnames(data)[index] : 
  replacement has length zero
AIC= 10813.546
> summary(mas)

Summary for distance analysis 
Number of observations :  1243 
Distance range         :  0  -  82.5 

Model : Half-normal key function with cosine adjustment term of order 2 
AIC   : 10813.55 

Detection function parameters
Scale coefficient(s):  
                 estimate           se
(Intercept)  3.6680796035 0.0448874309
MAS         -0.0007460832 0.0002518454

Adjustment term coefficient(s):  
             estimate         se
cos, order 2  0.16759 0.04247431

                        Estimate           SE         CV
Average p              0.2755222   0.01853751 0.06728136
N in covered region 4511.4327728 322.54635589 0.07149533
```
This is unexpected (and undocumented) behaviour.  Plot below shows PDF for MAS=c(60, 120); note deformed shape resulting from inclusing of an adjustment term as well. Do we want users to be able to fit such models or not?

![Rplot01](https://user-images.githubusercontent.com/330744/218477450-df3e81cb-acc5-4dda-9d08-c60db2f2fb6f.png)

**Comment by erex** [comment]
I remember a difference of opinion about this at our DistDev meeting. Len labelled it as a bug on 04Apr23, I agree with that assessment.

**Comment by lenthomas** [comment]
I think that this is trying to emulate the behaviour of DistWin, where no adjustments are fitted by default in MCDS analyses, but you can manually fit some.  I am fine with that as a strategy, so long as it's documented.  This would mean that if there's a covariate in the detection function and you don't set nadj or order then you get 0 adjustments; if you specify nadj or order then you get the specified adjustments.  I'm also happy with other suggested solutions.   Main thing is it's documented clearly in the online help.

I think the error messages are code bugs, aren't they?

**Comment by erex** [comment]
Right; documentation is inconsistent with code behaviour. Happy for documentation to reflect how code performs.  Understand the bug label comes from 

```
Error in covar_fields[i] <- colnames(data)[index] : 
  replacement has length zero
```

no idea what that means nor how it was triggered. Keep the bug label for that.

**Comment by lenthomas** [comment]
Tasks here are to: (1) check the error message that @erex showed in the example above; (2) check that one can ask for adjustment terms using `nadj` and/or `order` arguments when there are covariates; (3) check documentation is consistent with this; (4) check `mrds` package code and documentation also is as above.   Looks like current behaviour is not to fit adjustment terms when there are covariates, and this fine, so long as it's documented.  All of the above makes behaviour consistent with what DistWin does.

**Comment by LHMarshall** [comment]
The documentation has been amended and the code above no longer generates an error
<img width="463" alt="image" src="https://github.com/DistanceDevelopment/Distance/assets/1295691/ee9f3bae-0ab2-4945-bb30-51d1eaf5ace9">
