### ISSUE TITLE
Problem with dht2

### ISSUE THREAD

**Issue by GregoryJrd** [DistanceDevelopment/Distance#169]
Hi everyone, I am a new user of git do not hesitate to tell me if I did something wrong!

I'm conducting a stratified analysis with ds and dht2 from Distance (I've upload my data).
I manipulate the data of a line transect distance sampling, we detect clusters of animals which explain the column size.
I have 7 area, each one have been sampled  by one transect repeted several time a year. 
I have adjusted a detection function for each area and then I'd like to compute abundance/variance estimate for all the regions with dht2.
I got an error messsage which I could'nt solve by myself, would you have ideas about what I could have done wrong?
Here's the script I've used
Many thanks,
Gregory

[transect.txt](https://github.com/DistanceDevelopment/Distance/files/11486174/transect.txt)
[geostrat_stratif.txt](https://github.com/DistanceDevelopment/Distance/files/11486176/geostrat_stratif.txt)
[data_stratif_13_22.txt](https://github.com/DistanceDevelopment/Distance/files/11486177/data_stratif_13_22.txt)

library(ds)
#dtata
df<-read.table("data.stratif_13_22.txt")
line<-read.table("transect.txt")
stratif<-read.table("geostrat_stratif.txt")

df_bu<-subset(df, Region.label == "Buclon")
df_sl<-subset(df,Region.label == "Sosay-Lessy")
df_GB<-subset(df, Region.label == "Grand Bargy")
df_la<-subset(df, Region.label== "Leschaux-Andey")
df_pb<-subset(df,Region.label == "Petit Bargy")
df_pe<-subset(df,Region.label == "Peyre")
df_ra<-subset(df,Region.label == "Rasoir")

#fitting model 
bu.hr<-ds(data=df_bu, key="hr", adjustment=NULL,method = "BFGS",
       transect="line", truncation="5%")
sl.hr<-ds(data=df_sl, key="hr", adjustment=NULL,method = "BFGS",
          transect="line", truncation="5%")
GB.hr<-ds(data=df_GB, key="hr", adjustment=NULL,method = "BFGS",
          transect="line", truncation="5%")
la.hr<-ds(data=df_la, key="hr", adjustment=NULL,method = "BFGS",
          transect="line", truncation="5%")
pb.hr<-ds(data=df_pb, key="hr", adjustment=NULL,method = "BFGS",
          transect="line", truncation="5%")
pe.hr<-ds(data=df_pe, key="hr", adjustment=NULL,method = "BFGS",
          transect="line", truncation="5%")
ra.hr<-ds(data=df_ra, key="hr", adjustment=NULL,method = "BFGS",
          transect="line", truncation="5%")

model_ds<-c(bu.hr, sl.hr, GB.hr, la.hr, pb.hr, pe.hr, ra.hr)
IP_df_dht2 <- dht2(ddf=model_ds,observations =df, transects = transect, geo_strat = geo_strat1 , stratification = "geographical", strat_formula =~Region.label )

I get this message: Error in `$<-.data.frame`(`*tmp*`, "p", value = c(`2013-06-01_Buclon_75_2` = 0.369419677771411,  : 
  le tableau de remplacement a 81 lignes, le tableau remplacé en a 0
french part : new table has 81 rows, the old 0 
the subset df_bu has 81 row maybe the problem reside around this data.frame...

**Comment by erex** [comment]
Gregory

I've just skimmed your issue and have not looked at your code or your data.  But I expect it is not a software issue at the heart of the problem. Instead, I suspect your study design is at fault.  This statement of yours struck me as problematic:

> I have 7 area, each one have been sampled by one transect repeted several time a year.

If each stratum has but a single spatial replicate, then it is impossible to estimate a variance in the encounter rate between transects. Temporal replication does not solve the problem because in distance sampling, you are sampling space. Spatial replication is central to understanding the uncertainty in your density estimates.

Hence, I'm not surprised that `dht2` complains. Likewise, the first argument to `dht2` should be a **single** model object, not a concatenation of 7 model objects as you have done.

To reiterate, with your design, you cannot produce stratum-specific estimates because there is no spatial replication. Revisit what it is you wish to estimate and we will try to assist.

**Comment by GregoryJrd** [comment]
Eric
Thank you for your quick response. I was affraid of that kind of response, indeed the data I have does not come from a sampling program designed to perform distance sampling but from a monitoring program which aims to assess the dynamic of an epidemy in a mountain ungulate population. Since the monitoring take place in a mountain area its realisation isn't simple. In fact, the data collected was designed to allowed to performed different methods to see which could be the best (Mark resight, IPS and distance sampling).

Mark resight is quite effective and seems to give reliable estimate given the situation. Yet the population has a strong spatial structuration and we wonder whether distance sampling and its further developement such as DSM could give interesting insight of the population. 
As I said earlier the sampling isn't really designed as a regular distance sampling would required it. The transect aren't placed randomly since the observers have to follow hiking path or edges hence the distribution of the animals isn't independent of the position of the transect. Yet we obtain a distribution of the observed distance which comply with the one which is expected in a regular DS. Moreover we also have an independent sample of animal distribution thanks to GPS collar so that we can account for the heterogeneity of the distribution.
We already compute a modele with ds using transects as a covariable. It adjusted a detection function for each transect to account for the huge heterogenity. 
Since I am new to DS I thought that we could compute estimate of variance with dht2 considering each transect as a stratum, from what I understand now I should use the model transect as covariable.

Many thanks for your time,
Grégory

**Comment by erex** [comment]
Grégory--Given you recognise the challenges of this design (small number (7) of non-randomly placed transects), perhaps we can agree this is not a software issue (i.e. "problem with dht2"). If that is accurate, I will close the issue.

**Comment by GregoryJrd** [comment]
Dear Eric,
 I'd say yes, thank you again.
