### ISSUE TITLE
Transect-specific sampling fractions results printing error

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#179]
From [this email](https://outlook.office.com/mail/inbox/id/AAMkAGIyMzNiODc5LTZiMmEtNDJjZC05ZmY4LTI4NDMzZjg3OWIwMABGAAAAAABxWDR7YHXbTZlDNryVjk9mBwCZTNaQDzlSQZrYTi2nJ96DAAAA2tK6AAAT2HAbdtQpSa0hfAsv9XvmAAgpsvPMAAA%3D) on the list today, the `print` method for a `dht2` object cannot cope when `sample_fraction` is not a scalar.
<img width="756" alt="Screenshot 2024-03-04 at 8 25 01 PM" src="https://github.com/DistanceDevelopment/Distance/assets/330744/7067de56-62f4-4f82-811b-7841e8d66057">
Note, `dht2` itself does not complain, presumably performs the calculations, just cannot print them.

Error stems from this line of code
https://github.com/DistanceDevelopment/Distance/blob/5427008203fdda7a4b5f3c23a523110bd0ab0bcb/R/print.dht_result.R#L24

**Comment by LHMarshall** [comment]
Reproducable example with available dataset

```
data(minke)
# Add a sampling fraction
minke.samp.frac <- data.frame(Sample.Label = unique(minke$Sample.Label))
minke.samp.frac$fraction <- sample(c(0.5,1),
                                   nrow(minke.samp.frac), 
                                   replace = TRUE)
# first fitting the detection function
minke_df <- ds(minke, truncation=1.5, adjustment=NULL)
# now estimate abundance using dht2
# stratum labels are in the Region.Label column
minke_dht2 <- dht2(minke_df, 
                   flatfile=minke, 
                   stratification="geographical", 
                   sample_fraction = minke.samp.frac,
                   strat_formula=~Region.Label)
# could compare this to minke_df$dht and see the same results
minke_dht2
# can alternatively report density
print(minke_dht2, report="density")
```
