### ISSUE TITLE
Unexpected error: quitting. Numerical Server. Distance.ModGlobal.GenericRunBrowserItem

### ISSUE THREAD

**Issue by GlennW7** [DistanceDevelopment/Distance#183]
I am unable to run any analysis.
When i open up an analysis and click on run I receive the following message:
Unexpected error; quitting
![image](https://github.com/DistanceDevelopment/Distance/assets/174396122/0a0b3314-2508-4a0d-b08a-93b0522f4e1c)

After a minute I receive another error message:
"
Distance Internal error
The following error in Distance Numerical Server.
Source:D7NSvr.NServerItem.RunItem
Internal Error number: -2146959355.
Internal Error description: "Server execution failed".

(Error raised from:
Distance.ModGlobal.GenericRunBrowserItem)
(Error Source:D7NSvr.NServerItem.RunItem)
Error number: -2147211505)
"
![image](https://github.com/DistanceDevelopment/Distance/assets/174396122/71c7b911-6c15-47db-a095-e7ea9f60e0d6)

I have attempted an uninstall and re-install of Distance. I have restarted and completed a hard reset of the computer. 
I am still receiving this error which is preventing me from running any analysis. 

Regards,
Glenn

**Comment by erex** [comment]
Issue moved to [distance-bugs repo](https://github.com/DistanceDevelopment/distance-bugs/issues/215)

**Comment by LHMarshall** [comment]
@GlennW7 just to check in case your E-mail was following only this issue, I posted a reply in the issue Eric created regarding it. If you still need assistance please do contact us at the <distance [at] st-andrews.ac.uk> E-mail address too.
