### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#2]
Would like to have true point transect plots generated for point transect data.  Currently get g(x) function plotted when f(x) i.e. pdf is required

mrds:::plot.ds() was not built with point transects in mind.  Once upon a time Jeff had written mrpt; but it seems to have vanished.

**Comment by dill** [comment]
I believe `mrpt` was consumed into `mrds` but I don't know if it ever included a plotting function for f(r) in the point transect case.

The only lead I have is [`plotcode.r`](https://github.com/jlaake/mrpt/blob/master/mrpt/R/plotcode.r) from @jlaake's `mrpt` package.

**Comment by jlaake** [comment]
mrpt is on my github site jlaake/mrpt.

It was NOT absorbed into mrds.

**Comment by dill** [comment]
PDF plotting for point transects is included in `mrds` as of [8e5a5ef](https://github.com/DistanceDevelopment/mrds/commit/8e5a5ef8126cc12536e84de26060577d532d2d66).
