### ISSUE TITLE
GOF for binned data

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#20]
This explicitly returns NA in [this line of code](https://github.com/DistanceDevelopment/Distance/blob/master/R/summarize_ds_models.R#L64)

I would have expected instead that the object
```
gof <- gof_ds(model, chi=TRUE)$chisquare$chi1$p
```
would have been assigned

**Comment by erex** [comment]
I think there was a note to add a "digits" argument to kable() for fewer decimal places appearing in the tables

**Comment by dill** [comment]
Fixed in 3accf54.

**Comment by dill** [comment]
As for digits, there is already something in `kable()` to do this but perhaps we want to think about a `print` method for the table -- not sure how to reconcile this with printing in markdown etc though...

**Comment by dill** [comment]
This is closed save for the digits issue, which is an `mrds` issue. Moving that to [here](https://github.com/DistanceDevelopment/mrds/issues/26)
