### ISSUE TITLE
Ignoring distbegin and distend

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/Distance#22]
Distance exhibits unexpected (to me) behaviour when columns distbegin and distend are included in a flat file format (and possibly hierarchical file format also -- I didn't check that).  Basically, it seems to use distbegin and distend to identify cutpoints, but then ignores the values in these fields to work out which bins to put each observation -- instead it uses the distance field.  Seems to me that a distance field should not be required if there is a distbegin and distend field, and if it a distance field is there, it should be ignored.

For an illustration, grab the data file
https://www.dropbox.com/s/ppe3p80lqt818z8/mtor_ds_data.csv?dl=0
and then run the following code

```r
library(Distance)

#Read in data
mtor_ds_data<-read.csv("mtor_ds_data.csv")
#Fit function
res<-ds(mtor_ds_data,transect = "point", key = "hr", adjustment = NULL)
#Plot the pdf -- hmmm -- looks bad - clearly it's not reading the data correctly
plot(res,pdf=TRUE)
#Rename the distance column
colnames(mtor_ds_data)[7]<-"dist"
#Try again
res<-ds(mtor_ds_data,transect = "point", key = "hr", adjustment = NULL)
#Now it doesn't work -- it seems like it's just using 
# distbegin and distend to get the cutpoints -- but it's using
# distance for the actual distances
#So, create a distance column, and put in values in the right interval
mtor_ds_data$distance<-(mtor_ds_data$distbegin+mtor_ds_data$distend)/2
#Now try
res<-ds(mtor_ds_data,transect = "point", key = "hr", adjustment = NULL,)
#Plot looks better!  Well, at least the data look okay now.
plot(res,pdf=TRUE)
```

**Comment by erex** [comment]
Seems that there is an expectation that the recorded distance would be between distbegin and distend.

An unusual coding convention in these data, where distance "1" has an (understandable) distbegin/distend pair of (0,5), yet distance "2" lives between (5,10) and "3" is between (10, 20).

**Comment by dill** [comment]
@lenthomas do you have a response to @erex here?

In general I can drop the `distance` column when `distbegin`/`distend` exist and throw a `warning()`, would that be your prefered solution?

**Comment by lenthomas** [comment]
Yes, I think that's a sensible solution (drop the `distance` column when `distbegin` and `distend` exist and throw a warning).  That way the user doesn't get the false impression that the `distance` column has anything to do with estimation in this case.
