### ISSUE TITLE
Variance estimator to use?

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#23]
@dill 
I see in the last commit to Distance this morning you changed the default variance estimator to P3.  I've long since forgotten the deep discussions of var(n) matters of several months ago, but opening DistWin just today, I see this as the default var(n) calculation
![image](https://user-images.githubusercontent.com/330744/41604628-9a325616-73d7-11e8-9d81-5faf316b6e1a.png)

meaning that this will add another disparity for folks comparing DistWin and ds() results.  Is this intended?

**Comment by dill** [comment]
P3 is the only estimator available in `mrds`, the patch was only put there to avoid an auto-generated message that `dht()` had switched to P3.

The disparity was already there, this just makes sure that we don't tell users that the variance estimator is switched from a line one to a point one.

**Comment by erex** [comment]
thanks Dave, I found that auto-generated message inside D7 prerelease 24 that didn't incorporate that patch

**Comment by dill** [comment]
Ah though this only has an effect in Distance in R not a patch to mrds
