### ISSUE TITLE
Post-stratification (using Montrave as test case)

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#25]
### Using species as post-stratification criterion

Hadn't occurred to me to replace `Region.Label` by the post-stratification variable.  However, treating strata as a covariate the ability to have adjustment terms in the detection function is lost in this post-stratification situation.

I also note that the summary statistics for ds() and DistWin differ in the Montrave situation when there are repeated walks of the transects.  The covered area and effort calculated by ds() are both twice as large as the values reported by DistWin.  This causes encounter rate statistics to be twice as large for DistWin compared with ds().  However, the density is of the correct order of magnitude.

Slightly more troubling is the discrepancy in the calculation of degrees of freedom and knock-on consequences for confidence interval width.  Note this discrepancy is small for three of the four species, but for robins ds() df is only half df computed by DistWin.

#### R code from @dill 
```
birds <- read.csv("http://workshops.distancesampling.org/stand-intermed-2018/R_tutorial/montrave-line.csv")
# get effort right
birds$Effort <- birds$Effort * birds$repeats
birds$repeats <- NULL
birds$visit <- NULL
# stratification variable
birds$Region.Label <- birds$species
# pull in the extra sample labels for each spp
dummy_dat <- expand.grid(Sample.Label=1:19, species=c("w","r","g","c"))
dummy_dat$Region.Label <- dummy_dat$species
dummy_dat$Area <- 33.2
dummy_dat <- merge(dummy_dat,  unique(birds[,c("Sample.Label","Effort")]))
dummy_dat$distance <- NA
# join data.frames
birds <- rbind(birds, dummy_dat)
# fit model and get summary
library(Distance)
bird_df <- ds(birds, formula=~species, truncation=95, key="hr", convert.units=.1)
summary(bird_df)
```
#### R results

```
Model : Hazard-rate key function 
AIC   : 3045.928 

Detection function parameters
Scale coefficient(s):  
               estimate        se
(Intercept)  4.00890749 0.1432310
speciesg     0.07626653 0.2283094
speciesr    -0.09080365 0.1753809
speciesw     0.22391359 0.1676297

Shape coefficient(s):  
            estimate        se
(Intercept) 1.074037 0.2696813

                       Estimate          SE         CV
Average p             0.7305749  0.03512054 0.04807246
N in covered region 465.3868939 26.00107310 0.05586980

Summary statistics:
  Region  Area CoveredArea Effort   n  k        ER     se.ER      cv.ER
1      c  33.2      183.54   9.66  73 19  7.556936 1.0213625 0.13515565
2      g  33.2      183.54   9.66  32 19  3.312629 0.6239043 0.18834111
3      r  33.2      183.54   9.66  80 19  8.281573 0.8557845 0.10333598
4      w  33.2      183.54   9.66 155 19 16.045549 1.2038979 0.07503002
5  Total 132.8      734.16  38.64 340 76  8.799172 0.7296761 0.08292554

Abundance:
  Label  Estimate       se         cv       lcl      ucl        df
1     c 19.062314 3.171276 0.16636362 13.653023 26.61475  40.73998
2     g  7.912737 1.841317 0.23270297  4.976941 12.58030  41.33114
3     r 22.376042 3.174388 0.14186547 16.873742 29.67257  61.35939
4     w 34.831345 3.390685 0.09734579 28.657925 42.33463  49.75534
5 Total 84.182439 6.112531 0.07261053 72.959508 97.13173 181.36505

Density:
  Label  Estimate         se         cv       lcl       ucl        df
1     c 0.5741661 0.09552035 0.16636362 0.4112356 0.8016492  40.73998
2     g 0.2383355 0.05546137 0.23270297 0.1499079 0.3789247  41.33114
3     r 0.6739772 0.09561409 0.14186547 0.5082452 0.8937521  61.35939
4     w 1.0491369 0.10212906 0.09734579 0.8631905 1.2751394  49.75534
5 Total 0.6339039 0.04602810 0.07261053 0.5493939 0.7314136 181.36505
```

#### (some) DistWin results
```
                         Estimate      %CV     df     95% Confidence Interval
                        ------------------------------------------------------
 Stratum: c      Encounter rate summary                                           
                 n       73.000    
                 k       19.000    
                 L       4.8300    
                 n/L     15.114       13.52    18.00  11.392       20.051    
                 Left    0.0000
                 Width   95.000 
                         Estimate      %CV     df     95% Confidence Interval
                        ------------------------------------------------------
 Stratum: c                                                 
 Half-normal/Hermite    
                 D      0.64095       16.98    41.35 0.45606      0.90078    
                 N       21.000       16.98    41.35  15.000       30.000    
 Stratum: g                                                 
 Half-normal/Hermite    
                 D      0.25147       24.20    39.38 0.15523      0.40739    
                 N       8.0000       24.20    39.38  5.0000       14.000    
 Stratum: r                                                 
 Half-normal/Hermite    
                 D      0.69692       21.97    95.29 0.45290       1.0724    
                 N       23.000       21.97    95.29  15.000       36.000    
 Stratum: w                                                 
 Half-normal/Hermite    
                 D       1.0672       10.28    58.20 0.86912       1.3104    
                 N       35.000       10.28    58.20  29.000       44.000    
```

**Comment by dill** [comment]
Some slightly more modular code is mocked-up at https://github.com/dill/fancydht. That takes care of the covariates vs. adjustment terms issue. DoF requires more thinking than I an manage at the weekend.

**Comment by erex** [comment]
### Covered area and effort inconsistent with DistWin

Email from Peggy Bevan 08Aug18
> I have been struggling to understand how the package deals with visits to same point multiple times.  
I have 20 points, each visited 6 times, so I have put effort as 6 (120 visits in total). When I run the model (truncated at 100m) , the output gives the covered area as 3769911, which is 120*(100^2 * pi). So it is treating each visit as a new point, even though they have the same sample label. 

Miller in replied on 16Aug18 in [this issue](https://github.com/DistanceDevelopment/Distance/issues/24#issuecomment-413528218)
> Will reply on list then.

**Comment by dill** [comment]
Number of transects is fixed in fdaefa2.

**Comment by dill** [comment]
Discrepency in effort is down to whether one takes into account repeats. In `test.R` I use:

```r
birds$Effort <- birds$Effort * birds$repeats
```

to get effort, this gives

```r
> sum(unique(birds[,c("Sample.Label","Effort")])$Effort)
[1] 9.66
```

However, removing this line gives

```r
> sum(unique(birds[,c("Sample.Label","Effort")])$Effort)
[1] 4.83
```

as in Distance for Windows. How does Distance for Windows account for the repeat visits in the output above? AFAIK, we mutliplying effort by visits is the only mechanism we have in `dht` at the moment but we can add another method if there is one in Distance for Windows that's preferred.

**Comment by erex** [comment]
### Adjusting effort for repeat visits in DistWin
#### Line transects
![image](https://user-images.githubusercontent.com/330744/46282746-3e772100-c56a-11e8-8210-877f0a126241.png)
#### Point transects
![image](https://user-images.githubusercontent.com/330744/46282820-741c0a00-c56a-11e8-9df8-0e27aad6cdfc.png)

**Comment by dill** [comment]
So this wasn't done in the Distance for Windows examples above?

**Comment by erex** [comment]
Not sure what "this" you are referring to, but screenshot of DistWin project shows a field "Survey effort"

![image](https://user-images.githubusercontent.com/330744/46286659-d4fe0f00-c577-11e8-9f49-da09236b7a7d.png)

**Comment by dill** [comment]
The "this" refers to multiplying the effort by the number of visits.

NB. The post that starts this thread analyses the line transect Montrave data, your last post shows the point transect data.

**Comment by erex** [comment]
Screenshot of Montrave line transect data setup
![image](https://user-images.githubusercontent.com/330744/46289448-0a5b2a80-c581-11e8-9e9b-fcb120c4a38a.png)

using a multiplier to account for the double visits

**Comment by dill** [comment]
Okay, so to summarize my understanding so far (with some questions):

- there are 2 ways to account for multiple transect visits in Distance for Windows
  1. multiplying the effort column by the number of visits
  2. using "multipliers" (which may only 1 value, so transects must all be revisited the same number of times?)
- if ii. is used Distance for Windows does not report the correct effort in the results browser (assuming that the data in https://user-images.githubusercontent.com/330744/46289448-0a5b2a80-c581-11e8-9e9b-fcb120c4a38a.png and the results in https://github.com/DistanceDevelopment/Distance/issues/25#issue-362619364 are from the same project/analysis)
- unclear what happens if i. is used (I would guess results are then the same as `Distance`?)

**Comment by erex** [comment]
Mostly correct.  Effort is measured differently for points and for lines.  For points, it can only take on integer values, whereas for lines it is continuous.  (there is a further exception to the point issue when it comes to cue count surveys, but we'll ignore that for now).

Perhaps the launching point for tomorrow's DisDev discussions; are you leading that?

**Comment by erex** [comment]
I don't know what `fdaefa2` refers to.  Can only find [this](https://github.com/nu774/mp4fpsmod/commit/fdaefa27acaf7d90c6c7d4bb8a1d557554af8e9c)  hash ID

**Comment by dill** [comment]
commit on `fancydht`, link corrected to [this one](https://github.com/dill/fancydht/commit/fdaefa2a7c39a51c5ab00f981b3478169145f65a) above.

**Comment by erex** [comment]
OK--I'll give it a whirl

**Comment by dill** [comment]
Closing this issue as `dht2` handles/will handle this situation.
