### ISSUE TITLE
How to get the position of a value in a distance matrix?

### ISSUE THREAD

**Issue by saifsikdar** [DistanceDevelopment/Distance#27]
Hi, 

I have run a chi-square test of a distance matrix of my data and found that the value "0.841759306705294" is an outlier.  Now, I want to findout which of row vs coloumn have this value so that I can remove the outlier samples from my dataset.  Can you please help me how to find the positions of 0.841759306705294? Thank you!

The code I have run:
>ps_gfvsSPF_wunifrac <- phyloseq::distance(ps.prop_GFvsSPF, method = "wunifrac")
>chisq.out.test(ps_gfvsSPF_wunifrac)

**Output:   chi-squared test for outlier
data:  ps_gfvsSPF_wunifrac
X-squared = 2.3688, p-value = 0.1238
alternative hypothesis: highest value 0.841759306705294 is an outlier**

Then,
>which(ps_gfvsSPF_wunifrac == 0.13844566, arr.ind = TRUE)

But, i received output:
**integer(0)**

The attach is the snapshot of how the distance matrix looks like

![dist](https://user-images.githubusercontent.com/34520963/49761518-94f88e00-fc84-11e8-97b3-a4776e6eb5ed.JPG)

**Comment by erex** [comment]
Saif

I'm afraid you've sent this issue to the wrong repository.  You should contact the maintainer of the `physoseq` package, rather than the `Distance` package.

The package you want is maintained here
```
The phyloseq package is actively and openly developed on GitHub:

https://github.com/joey711/phyloseq
```
