### ISSUE TITLE
Add a function that creates a data.frame with candidate detection functions

### ISSUE THREAD

**Issue by fsdias** [DistanceDevelopment/Distance#3]
The table would list the "key function", adjustment terms, AIC/AICc, number of parameters, results from goodness of fit tests. E.g.

df_select(DF1, DF2, DF3,...)

The result would be a data.frame that looks like this table:

![screenshot from 2015-09-30 09 24 15](https://cloud.githubusercontent.com/assets/5689181/10188161/1faf8ea4-6755-11e5-94ea-5456e2d8ebef.png)

**Comment by erex** [comment]
Good idea.  We will put that on our list of enhancements.

**Comment by dill** [comment]
I have some (very kludgey) code to do this (below), that I'll clean-up and put in `Distance` at some point. I'll paste it here in case it's useful:

```{r}
# models should be a list of model objects generated from calls to ds()
make_table <- function(models){

  extract_model_data <- function(model){
    c(summary(model)$ds$key,
      model$ddf$ds$aux$ddfobj$scale$formula,
      model$ddf$criterion,
      ddf.gof(model$ddf, qq=FALSE)$dsgof$CvM$p,
      summary(model)$ds$average.p,
      summary(model)$ds$average.p.se
    )
  }

  res <- as.data.frame(t(as.data.frame(lapply(models, extract_model_data))),
                        stringsAsFactors=FALSE)

  res[,3] <- as.numeric(res[,3])
  res[,4] <- as.numeric(res[,4])
  res[,5] <- as.numeric(res[,5])
  res[,6] <- as.numeric(res[,6])

  colnames(res) <- c("Key function", "Formula", "AIC", "Cramer-von Mises $p$-     value",
                     "$\\hat{P_a}$", "se($\\hat{P_a}$)")

  res[["$\\Delta$AIC"]] <- res$AIC - min(res$AIC, na.rm=TRUE)
  res <- res[order(res$AIC),]

  res
}
```

**Comment by dill** [comment]
As of c59d4f7e2a95d8fd192d116df1a226c7fb645d48 this is implemented in `summarize_ds_models`.

**Comment by dill** [comment]
Comments welcome on how to improve this, of course!
