### ISSUE TITLE
`newdht` branch merge?

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#30]
As of standrews-2019 software instructions states download the master brance of Distance, that branch will need to have the new functions required for the workshop.

**Comment by dill** [comment]
I did this merge yesterday, so this should be fine.

**Comment by erex** [comment]
I'm not savvy enough in the ways of github, I don't see the merge in the commits log

**Comment by dill** [comment]
it was a fastforward, so it doesn't look as messy as usual, but looking at [the file listing](https://github.com/DistanceDevelopment/Distance/tree/master/R), you can see those new files are there.

**Comment by erex** [comment]
thanks; I'm clueless about fastforward, should have thought of looking at the R directory itself.
