### ISSUE TITLE
remove amakihi dataset from this package

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#37]
The `amakihi` dataset in `dsdata` is a faithful representation of the DistWin project data.  The version here is odd in that the data does not contain either Sample.Label or Region.Label.  Missing Region.Label is no great concern, but without Sample.Label encounter rate cannot be computed.

If `dsdata` gets folded into `Distance` the duplication will probably be resolved.

**Comment by erex** [comment]
Speaking of merging `dsdata` with `Distance`:
given I'm writing vignettes for the `Distance` package, but each vignette begins with `library(dsdata)`, should we resolve whether the packages are going to be merged before the vignettes are finalised?

**Comment by dill** [comment]
Were there any arguments against putting the data from `dsdata` into `Distance`? If not I will merge when I have a moment.

**Comment by erex** [comment]
The right thing to do is to have the data sets inside the package.  Unfortunately, that will require re-writing the intro workshop exercises and the under-construction vignettes to remove reference to the `dsdata` package.

Several of the workshop exercises were already in need of repair in light of the renaming of all of the Montrave wren data sets.

**Comment by dill** [comment]
Am I right in thinking that removing `amakihi` from `Distance` now will not disrupt your workshop?

**Comment by erex** [comment]
Please **do not** remove `amakihi` from `Distance`.  The data **is** used in the workshop I will deliver in May.  

This issue dates from Oct19, when here was still a `dsdata` package in the mix.  You 25Oct commit that merged `dsdata` with `Distance` resolved the issue.

**Comment by dill** [comment]
Got it will close this then.
