### ISSUE TITLE
Built-in bootstrap summary function

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#43]
@dill I recall Len suggesting that the *standard* summarising function be included in the package, rather than the user having to produce it.  Is that going to happen?  The reason I ask is that I'm building the *variance* vignette and wish to know whether to describe how to build the function, or simply note that it lives in the package.

I'll move on to other vignettes, no need to do this immediately on my account, I've plenty more.

**Comment by erex** [comment]
while I have your attention, unrelated to variance estimation.  How do you prefer I cite the Distance package in the vignettes?

The original vignettes cite this:

Miller DL (2017) Distance: Distance Sampling Detection Function and Abundance Estimation. R package version 0.9.7. should be 0.9.9 but not on CRAN https://CRAN.R-project.org/package=Distance

but 
```
> citation("Distance")

To cite Distance in publications use:

Miller DL, Rexstad E, Thomas L, Marshall L, Laake JL (2019).
“Distance Sampling in R.” _Journal of Statistical Software_,
*89*(1), 1-28. doi: 10.18637/jss.v089.i01 (URL:
https://doi.org/10.18637/jss.v089.i01).

A BibTeX entry for LaTeX users is

  @Article{,
    title = {Distance Sampling in {R}},
    author = {David L. Miller and Eric Rexstad and Len Thomas and Laura Marshall and Jeffrey L. Laake},
    journal = {Journal of Statistical Software},
    year = {2019},
    volume = {89},
    number = {1},
    pages = {1--28},
    doi = {10.18637/jss.v089.i01},
  }
```

is that what you prefer?

**Comment by dill** [comment]
re: variance function, yes I intend to write  default method. Will get to that.

re: citing, the paper is best.

**Comment by dill** [comment]
@erex how does that look for you?

**Comment by erex** [comment]
Thanks Dave.  I think the function will work in the first instance.  What is lacking in the documentation is heaching the users how they can modify it for their own purposes.  If I saw that function, I wouldn't really get a grasp on what it is doing with the arguments passed in and what to do with the object passed out.

**Comment by dill** [comment]
Perhaps this is a good topic for an examples site vignette, linked through from the help? Potentially too complicated to explain in the documentation?

**Comment by erex** [comment]
no argument that more description could be provided, perhaps in a vignette.  where does that leave us?

**Comment by dill** [comment]
in the interests of getting this on CRAN pre-7th Feb, I'll just add a note to the doco for the example summary leading people to the examples site. There are examples in the variance estimation vignette at the moment (albeit not much more complex), we can then expand on this offering later. Does that seem reasonable?

**Comment by erex** [comment]
Yes, this isn't something that needs remedy before CRAN submission.  I'm just thinking this is an area where user questions will arise, trying to be proactive to prevent too many questions from coming up.

The examples site is exactly the place where we have the flexibility to expound on these matters.

**Comment by dill** [comment]
okay will do this and close this issue (we can create another for the examples site todo list perhaps?)
