### ISSUE TITLE
NEWS file doesn't appear in HTML documentation index

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#45]
`news(package="Distance")` works (on Dave's machine) but the `NEWS` file is not linked from the package HTML doco page.

**Comment by dill** [comment]
switching to non-markdown extension fixes this for me (e420c0f)

**Comment by lenthomas** [comment]
Hi @dill, I have installed v1.0.1 on my machine, but when I type
news(package="Distance")
I get the attached blank screen on my browser (Firefox).

![Annotation 2020-06-30 092316](https://user-images.githubusercontent.com/129519/86102690-c11c6f80-bab3-11ea-85d1-e6000ef801c3.jpg)

I must admit to not understanding your comment of 21 Apr, but it does seem that something still needs fixing here.  Let me know if you want me to test any fix you implement on a non-Mac machine.

**Comment by dill** [comment]
Can you try a github install via `devtools` and see what happens when you do that?

**Comment by dill** [comment]
re: comment 21 April. The issue for me at least was that the filename `NEWS.md` was not automatically picked-up by R as being the news file where as it was looking for a file called `NEWS` (IIRC!)

**Comment by lenthomas** [comment]
> Can you try a github install via devtools and see what happens when you do that?
I had done that already to install 1.0.1
```
library(devtools)
install_github("DistanceDevelopment/Distance")
news(package="Distance")
```
Gave the blank output on my browser.

**Comment by dill** [comment]
somehow blank on my machine now too. Will look into it.

**Comment by dill** [comment]
can you test the above commit @lenthomas?

**Comment by lenthomas** [comment]
Thanks - whatever you did seems to fix it.  If it works on your machine now also, I believe you can close the issue again.

**Comment by dill** [comment]
Great! Very weird this worked fine for me previously then broke again, then the fix is just removing the word "version" in each release header but whatever...
