### ISSUE TITLE
Examine distribution of predicted \hat{P}

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#47]
particularly when employing covariates (and consequent HT-like estimator), indicate if there are detections with small \hat{P}s that can be unduly influential, as is produced by Distance for Windows

![image](https://user-images.githubusercontent.com/330744/75993937-225f7800-5ef2-11ea-9b09-44f6ffa48f4c.png)
using something as simple as

```
table(cut(dsobject$ddf$fitted, seq(from=0, to=1, by=0.1)))
```

**Comment by dill** [comment]
I've pushed code to do this to the mrds repo. Let me know if that's what 
your thinking of and I'll add the Distance wrapper.

**Comment by erex** [comment]
Please try again:

```
Type 'q()' to quit R.

> remotes::install_github("DistanceDevelopment/mrds")
Downloading GitHub repo DistanceDevelopment/mrds@master
√  checking for file 'C:\Users\erexs\AppData\Local\Temp\RtmpIREN3D\remotesb99c51b549d8\DistanceDevelopment-mrds-57f5f45/DESCRIPTION' (401ms)
-  preparing 'mrds': (1.1s)
√  checking DESCRIPTION meta-information ... 
   Warning: C:/Users/erexs/AppData/Local/Temp/RtmpqcslgT/Rbuild257c35f82f63/mrds/man/p_dist_table.Rd:20: unknown macro '\hat'
-  checking for LF line-endings in source and make files and shell scripts (684ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'mrds_2.2.2.tar.gz'
   
Installing package into ‘C:/Users/erexs/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'mrds' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) C:/Users/erexs/AppData/Local/Temp/RtmpQJ8da9/R.INSTALL4a1c493d5c4f/mrds/man/p_dist_table.Rd:20: unknown macro '\hat'
ERROR: installing Rd objects failed for package 'mrds'
* removing 'C:/Users/erexs/Documents/R/win-library/3.6/mrds'
* restoring previous 'C:/Users/erexs/Documents/R/win-library/3.6/mrds'
Error: Failed to install 'mrds' from GitHub:
  (converted from warning) installation of package ‘C:/Users/erexs/AppData/Local/Temp/RtmpIREN3D/fileb99c5b90676c/mrds_2.2.2.tar.gz’ had non-zero exit status
```

**Comment by dill** [comment]
fixed. Interestingly this installs with a warning on my machine, rather 
than falling over...

**Comment by erex** [comment]
looks like it does the trick; I might re-name the first column something like `p-hat`.

Could stand to have a bit more doco, maybe an example.

Doco should at least cite Chapter 3 of the Green book.  Here is the final paragraph of that chapter, that could also be plagarised for the doco.

> Because the methods of this chapter are based on a Horvitz–Thompsonlike
estimator, in which the inclusion probabilities are estimated, abundance
estimates can be sensitive to errors in the estimated probabilities.
The estimator is based on $\sum 1/  \hat{P}_a(zi)$, which means that the sensitivity
is greater for smaller P_a(zi). As a rough guide, we recommend that the
method be not used if more than say 5% of the  $\hat{P}a(zi)$ are less than 0.2,
or if any are less than 0.1. If these conditions are violated, the truncation
distance w can be reduced. This causes some loss of precision relative to
standard distance sampling without covariates.

```
p_dist_table(amak.hr.obs.mas$ddf, proportion = TRUE, bins = seq(from=0.1, to=0.5, by=.05))
          p count proportion
 0.1 - 0.15     0      0.000
 0.15 - 0.2   167      0.134
 0.2 - 0.25   106      0.085
 0.25 - 0.3     0      0.000
 0.3 - 0.35   105      0.084
 0.35 - 0.4   410      0.330
 0.4 - 0.45   394      0.317
 0.45 - 0.5    61      0.049
Range of probabilities:  0.16 - 0.47
```

**Comment by dill** [comment]
Added along with compatability with `Distance` models.
