### ISSUE TITLE
Error traps for `dht2`

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#49]
A fellow is using `dht2` in a mildly random way and exposing perhaps some error traps that could be introduced.  Exerpt from email below:

He has included year as covariate in detection function, but is confused about appropriate choice of `stratification` argument.  Apparently all of his choices produce results, but probably should not.
```
My data are in the df `sheep’ : names(sheep)
[1] "Region.Label" "Area"         "Sample.Label" "Effort"       "size"         "distance"    
[7] "year” 

So I tried          yearests <- dht2(ddf=uct5, flatfile=sheep, strat_formula = ~year, convert_units = convert, stratification = "object”)  

Which gave the error message:
Error in x[!dup, ] : (subscript) logical subscript too long

In addition: Warning message:
In `[<-.data.frame`(`*tmp*`, flatfile$Sample.Label %in% sl_diff,  :
  provided 8 variables to replace 7 variables

So I tried          yearests <- dht2(ddf=hnt5, flatfile=sheep, strat_formula = ~year, convert_units = convert, stratification = "object”)  

Which gave me
Warning messages:
1: In `[<-.data.frame`(`*tmp*`, flatfile$Sample.Label %in% sl_diff,  :
  provided 8 variables to replace 7 variables
2: In `[<-.data.frame`(`*tmp*`, flatfile$Sample.Label %in% sl_diff,  :
  provided 8 variables to replace 7 variables 

but provided answers that I will come back to. 

I also tried        yearests <- dht2(ddf=hnt5, flatfile=sheep, strat_formula = ~as.factor(year), convert_units = convert, stratification = "object”)  

which gave me
Error in `[.data.frame`(bigdat, , c("Sample.Label", stratum_labels)) : 
  undefined columns selected

In addition: Warning message:
In `[<-.data.frame`(`*tmp*`, flatfile$Sample.Label %in% sl_diff,  :
  provided 8 variables to replace 7 variables
```

If I have, then it might be worth renaming the “geographical” option 

geographical
if each stratum represents a different geographical areas and you want the total over all the areas

to something like

section

if each stratum represents a different geographical area or time.

**Comment by dill** [comment]
Had a bit of a think about this. It's quite hard work out what to do here...

For example, the first case above: if we have our flatfile for `sheep`, we know that `year` varies at the level of the geo/temporal strata. But that's not obvious unless you understand the data structure. Even if we know that `year` varies at the level of the `geo_strat` table, once it's in a flatfile, it's impossible to work out whether it was collected at the individual level and just happens to be varying in the same way as our geo stratification levels.

Clearly **something** goes wrong though, so perhaps it's worth digging into `sheep` to find out. With a synthetic example I cooked up I got the following error:

```
Error in dht2(ddf = list(call = ddf(dsmodel = ~cds(key = "hn", formula = ~1),  :
 
  >1 Area defined for a single stratum label, check data
```

which is not hugely informative but better than what's reported above... We might need to have another chat about this at some point, as it's not 100% clear to me if/how we move forward in the flatfile case.

The final case is a clear bug in how I've implemented the formula stuff, as the `as.factor` is not being applied correctly to the `data.frame` internally and then can't be found. I'll get on that.

**Comment by dill** [comment]
I can now reproduce the error and will look into it further...

**Comment by dill** [comment]
errors now don't occur for `stratification="object"` but that doesn't necessarily "solve" the issue...

**Comment by dill** [comment]
Do you have further thoughts on this given my comments above on how this is hard to work out given the structure of the data?

**Comment by erex** [comment]
no obvious solutions, guess we'll wait for further problems to arise

**Comment by dill** [comment]
In which case I'll close this issue and we can open another when futher problems arise.
