### ISSUE TITLE
More forgiving field names

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#51]
Correspondent to the list wasn't getting satisfactory results from a simple analysis.  My response included this

* the ds() function is fussy about the column name for group size: it must be lower case; that's what line 4 does
    * this explains why the estimates you were producing did not make sense; not recognising that there were groups (because size was not recognised), the estimates you produced were abundance of groups.

I know field names are spelled out in `?flatfile` but could code be allowed to accept either upper or lower case field names?

**Comment by dill** [comment]
I'm a little wary of allowing multiple options (what if the user supplies both `size` and `Size`? What about `SiZe` too?) The number of options gets quite large for e.g., `Sample.Label`...

`size` is special as it's not required and filled-in by default, we could warn when this is being filled-in?

**Comment by dill** [comment]
recommend we throw a `warning()` when matches are made via some mechanism like `tolower(colname)==tolower(desiredname)`
