### ISSUE TITLE
Ability to specify y-axis label in plotting

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#52]
Question to the list from Antonela Marozzi <antomarozzi@gmail.com

> Hello dear all, this is a simple question but I am not sure how to solve it. I am using Rdist and I am plotting the models of my density estimations, but I need that the axes labels be in Spanish. When I set the names of the labels in the way I usually do it in R I get this warning message. 

> op<-par(mfrow=c(3,3),bty="l")
> plot(hr08_null690_site,main="2008",nc=5,xlab="Distancia",ylab="Probabilidad de detección")
Error in histline(hist.obj$density, breaks = breaks, lineonly = FALSE,  : 
  formal argument "ylab" matched by multiple actual arguments

> Is there any other way of changing the axes' names in the Distance package?

Her rationale is compelling, being able to specify labels in languages other than English.

**Comment by dill** [comment]
Agree that this is a good idea. I know there is a mechanism for 
internationalisation in R packages, I'll look into it.

**Comment by dill** [comment]
added ylab in https://github.com/DistanceDevelopment/mrds/commit/50564a00a58a9d77031e974a381922e773d91f06
