### ISSUE TITLE
sparse data set for which hr fit is stupid

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#53]
Sent by a user
[import_data_missions_CeTO_nomenclature_Sa.txt](https://github.com/DistanceDevelopment/Distance/files/4450913/import_data_missions_CeTO_nomenclature_Sa.txt)

No complaint provided by `ds` (or `mrds`).  Really poor fit

```
vanessa <- read.csv2("C:/Users/erexs/Downloads/import_data_missions_CeTO_nomenclature_Sa.txt",
                     sep="\t", dec=",")
names(vanessa)[9] <- "size"
hist(vanessa$distance)
library(Distance)
conv <- convert_units("meter", "kilometer", "square kilometer")
simple <- ds(vanessa, truncation="10%", convert.units = conv, key="hn")
plot(simple)
hr <- ds(vanessa, truncation="10%", key="hr", adjustment = NULL,
         convert.units = conv)
summary(hr)
plot(hr)
simple.size <- ds(vanessa, truncation="10%", convert.units = conv, key="hn",
                  formula = ~size)
AIC(simple,  simple.size, hr)
```

When bringing in size as covariate, AIC seems to go very strange.  Is this just a data set that's too small to produce anything meaningful?

**Comment by dill** [comment]
This fit does indeed look horrible (looking at QQ plots C-vM tests etc):

```
> gof_ds(simple)

Goodness of fit results for ddf object

Distance sampling Cramer-von Mises test (unweighted)
Test statistic = 0.454825 p-value = 0.0519762
> gof_ds(simple.size)

Goodness of fit results for ddf object

Distance sampling Cramer-von Mises test (unweighted)
Test statistic = 0.926402 p-value = 0.003665
> gof_ds(hr)

Goodness of fit results for ddf object

Distance sampling Cramer-von Mises test (unweighted)
Test statistic = 0.609866 p-value = 0.021161
```


 Have you tried analysing this in Distance for Windows to see what it produces? This would give some indication of whether it's an optimisation issue for us or down to the data being bad.

**Comment by erex** [comment]
no, I have not

**Comment by lenthomas** [comment]
I just tried it.  Distance for Windows hazard rate with no covars and 10% truncation:
![Annotation 2020-04-21 1345131](https://user-images.githubusercontent.com/129519/79867781-cdf75580-83d6-11ea-9db6-717b5d084a65.jpg)
![Annotation 2020-04-21 1347471](https://user-images.githubusercontent.com/129519/79867785-ce8fec00-83d6-11ea-9f6b-00b3d141b704.jpg)
![Annotation 2020-04-21 13474712](https://user-images.githubusercontent.com/129519/79867787-ce8fec00-83d6-11ea-9242-eb0acd6e592c.jpg)
![Annotation 2020-04-21 134747123](https://user-images.githubusercontent.com/129519/79867788-cf288280-83d6-11ea-8a1f-cba3d9657cb8.jpg)

With hazard rate and cluster size as a covariate:
![Annotation 2020-04-21 134747123](https://user-images.githubusercontent.com/129519/79868031-39d9be00-83d7-11ea-87be-fc3e8ff8133b.jpg)
![Annotation 2020-04-21 1347471231](https://user-images.githubusercontent.com/129519/79868033-3a725480-83d7-11ea-82f7-016e0ed0d893.jpg)
![Annotation 2020-04-21 13474712312](https://user-images.githubusercontent.com/129519/79868034-3b0aeb00-83d7-11ea-9b39-daff78d0edf2.jpg)
![Annotation 2020-04-21 134747123123](https://user-images.githubusercontent.com/129519/79868037-3b0aeb00-83d7-11ea-9491-0ce95244f9f0.jpg)

**Comment by erex** [comment]
Second example of this odd behaviour on the part of the hazard rate key in conjunction with a covariate for mildly spiked data was described in a [post to the list](https://groups.google.com/forum/#!topic/distance-sampling/quwxyV4x0_k) dated 12Jun20

**Comment by dill** [comment]
I looked into the first of these more thoroughly.

The issue seems to be that there is a very large spike near zero:

![Screenshot 2020-06-30 at 10 12 26](https://user-images.githubusercontent.com/1953/86107832-473bb480-baba-11ea-84b1-1c46f197e9de.png)

This seems to lead to the shape parameter being estimated to be zero for any hazard-rate model. I was able to get more reasonable (in terms of model convergence) results by binning the distances to avoid the spike (bins of size 100 get around that awkward first spike). BUT then the model still won't fit with size (I can get it to fit if I bin the group size too, fwiw).

In terms of things we can do beyond this data set: perhaps a warning when the shape parameter is close to 0? As in that case we're heading to a model without a shoulder, which we don't think is realistic.

**Comment by erex** [comment]
I favour your suggestion of issuing some sort of a warning, the tricky part being the criterion for generating the warning.  I second your suggestion of triggering a warning when the shape parameter becomes tiny and the fitted shape approaches a negative exponential.

It would be best if ds() not be silent about fitting such a model to such data.  Users that don't closely scrutinise model output will see no complaints from the software and happily report an abundance estimate that is wildly too large because of the fitted shape induced by the spike.  As you say, we do not give the users the option of fitting a negative exponential key function, we should close off the option of being able to approximate the negative exponential via the hazard rate.

**Comment by dill** [comment]
The criterion has been the reason I've been putting off making this fix. It seems safe to throw this when the scale is pretty much numerically zero (`scale < sqrt(.Machine$double.eps)`). We might be able to go bigger than that, but perhaps the best start point for now to avoid generating too many warnings. For the data above, the scale parameter is estimated to be zero, so this issue would have been caught.

**Comment by erex** [comment]
Seems plausible.  

Awkwardly, setting the criterion to a very small number reduces the number of warnings thrown.  But I wonder if we want to start with a large criterion and adjust downward?

The reason I say this is if a warning **should** be thrown because the fit is **nearly** exponential, we won't hear about those cases from our users if the criterion is really small (no warning issued, users are happy, no reason to report the behaviour).  Alternatively, if the criterion is set "large", it will set off "false positives" with a more likely result being a query to the list "why did I get this warning".  That is the way we can measure whether we get too many warnings and need to adjust the criterion downward.

Perhaps this is being contrary and overthinking the problem.

Happy with whatever you decide to do.

**Comment by lenthomas** [comment]
Just checking, @dill , when you said earlier "This seems to lead to the shape parameter being estimated to be zero for any hazard-rate model", did you mean "one" rather than "zero"?  Assuming yes, how about using 1.01 as the criterion for throwing a warning?  I have scientific basis for this, except that it's 1% more than 1.  Not sure what the warning might say, but perhaps something like "Warning, estimated shape parameter of hazard rate function is close to 1, possibly indicating a problem with the distance data."  Happy to hear better alternatives!

**Comment by dill** [comment]
Ah yeah sorry, 0 on the log scale :)

**Comment by dill** [comment]
I had thought of a similar idea @lenthomas but I'm not super-happy about putting some arbitrary number in there.

@erex: it is tempting to use this to collect some data, but I think the false positive rate may make people think that there are problems in our estimation procedure if it pops up too often (if we set it too large). At least in the extreme case we know something has gone wrong (the parameter has been estimated at its bound in the optimisation).

As for the message I think it has to refer to the log scale else the contents of `$par` and `summary` will be jarring. How about

```
Warning: estimated hazard-rate scale parameter close to 0. Possible problem in data (e.g., spike near zero distance).
```

which adds some information on what is actually happening?

**Comment by erex** [comment]
I hadn't thought about the false positive leading to suspicion of the optimisation routine.  I think you're right.

Happy for message to use the log scale (perhaps say "scale parameter estimated on log scale close to 0..."

Best for messages to be informative, including information about the data

**Comment by lenthomas** [comment]
Yes, I agree with @erex it needs to be clear that it's on the log scale.  Happy with your text otherwise @dill.

**Comment by dill** [comment]
I've made commits to `Distance` and `mrds` to produce the following error:

```
Estimated hazard-rate scale parameter close to 0 (on log scale). Possible problem in data (e.g., spike near zero distance).
```

I've added these in a separate branch to merge-in post next week's workshop.

**Comment by erex** [comment]
thanks for the separate branch; phrasing of message looks good
