### ISSUE TITLE
density estimates without study area size

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#56]
originally from #26, @erex asks "`dht` out to produce a density estimate when study area size is not specified"

**Comment by dill** [comment]
This case is handled already but I've added documentation to this effect in `mrds`.

**Comment by erex** [comment]
My interpretation is that `Area` is a required field if either an abundance or density estimate is required.  If the `Area` field is 0, then only a density estimate is produced.

What I had requested (and poorly worded as "study area size is not specified") is a density estimate be produced when the `Area` field is not present in the data frame.  Therefore these would be the outcomes of three possible cases:

- no `Area` field present in data frame
    - density estimate produced
- `Area` field present and set to 0
    - density estimate produced
- `Area` field present and non-zero
    - density and abundance estimate produced

rather than the current situation where
- no `Area` field present in data frame
    - no density estimate produced, only detection function fitted 
    - N_a is estimated, but not covered area, so D-hat cannot be estimated

**Comment by lenthomas** [comment]
I largely agree, although I don't see that `Area` is a requred field if a density estimate is required, and indeed that is one of the cases you give (no `Area` field should produce a density estimate).  I agree that no `Area` field can be treated the same way as an `Area` field with an area of 0 (or `NULL` or `N/A`?): software can produce estimates of covered area, N_a, and density -- but not study area abundance.

**Comment by erex** [comment]
my main point is that `Area` need not be a required field and if it is absent, a density estimate should be produced.  Current behaviour if `Area` field is absent is **not** to produce a density estimate, which I would like to have changed.

so the issue remains closed, unless @lenthomas reopens

**Comment by dill** [comment]
This turned into quite a saga and I'd typed it all up then github refreshed the page and lost it, so I'm afraid you only get the abridged, annoyed version...

**First off:** there was a bug in assigning the `Area` column in `dht` [here](https://github.com/DistanceDevelopment/mrds/blame/5eade01f33067a72b691889321b1272b81c5a441/mrds/R/dht.R#L189), fixed [here](https://github.com/DistanceDevelopment/mrds/commit/4b64af0633d435fd353e84a79359dd660e611f77).

**Second:** if we don't have an `Area` column, we have 1 of the following situations:

1. "Lazy": Want densities but doesn't want to input areas. Fine, in this case I think our usual estimation is okay.
2. "Covered area only": We want to get density estimates for the case where the covered area == study area. In this case we need to set `varflag=0` and use the binomial estimator for the number of observations (per Borchers et al, 1998 eqn 13) *but* `dht.se` caveats this with "This estimator is only useful if the sampled region is the survey region and **the objects are not clustered**; this situation will not occur very often".

@lenthomas / @erex do you think my reasoning on 1. above is correct or do we need to use the binomial estimator in that case too?

If I'm right about 1., I think we can't just assume one or the other, so I'm not sure whether we should allow this option if we don't know the intentions of the user.

FYI: Currently the `dht` options (aside from the ER estimator codes from Fewster et al) are not exposed to the user. `varflag` could be exposed but what the default behaviour should be is more tricky (and would involve more documentation/`warning`s etc).

**Comment by erex** [comment]
When I raised this issue, it was prompted by list questions from users who had failed to include an Area column.  I request that the R package perform in the manner of DistWin when Area is not provided.

### Unknown Study Area Size
> If you don't know the size of the study area you sampled, you can obtain density estimates from Distance, but not abundance estimates.
> When entering your data, leave the area of each stratum at its default value of 0. When you come to analyze the data, Distance will automatically detect that the area is 0 and will not provide an abundance estimate.

_page 127 of DistWin Users Guide_

**Comment by dill** [comment]
Okay so from reading the Distance for Windows user manual (p. 153) I think we're in my 1. above and that the varflag does not need to be set to 0.

**Comment by lenthomas** [comment]
Yes, @dill, I agree.  The case where you are only interested in making inferences about the number of animals within the covered area is a very rare one, and so I am totally fine with making users call dht explicitly and set the varflag in this situation.  You might want to add something about it in the ds() documentation -- i.e., tell them what the variance assumption is in ds() and how they can get additional flexibility by calling dht explicitly -- up to you!

**Comment by dill** [comment]
I think is should now be addressed in 598957f.
