### ISSUE TITLE
Effective Strip Width

### ISSUE THREAD

**Issue by jmsigner** [DistanceDevelopment/Distance#58]
What would be recommended way to extract the expected strip width (ESW), I saw that it is possible with `predict` in the development version, but was wondering if the ESW is also saved somewhere?

**Comment by erex** [comment]
Johannes

ESW is simply truncation distance multiplied by $P_a$.  For simple models without covariates, you can compute ESW like this, using `ducknest` data as an example:

```
library(Distance)
data("ducknest")
cu <- convert_units("meter", "kilometer", "kilometer")
simple <- ds(ducknest)
tmp <- summary(simple)
averagep <- tmp$ds$average.p
averagep.se <- tmp$ds$average.p.se
w <- tmp$ds$width
esw <- w * averagep
esw.se <- sqrt(averagep.se^2 * w^2)
esw
esw.se
# note: SE(ESW) should be same as SE(p)
```

**Comment by dill** [comment]
Potentially a less labour-intensive solution is using `predict` and the `$ddf` component of the fitted model:

```r
library(Distance)
data("ducknest")
simple <- ds(ducknest)
ps <- predict(simple$ddf, esw=TRUE)
```

This also scales better to the covariate case.
