### ISSUE TITLE
Amakihi chestnut

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#59]
Probably the fault of `mrds` but I place here for the moment; treading over old ground, I know.

Fitting a single covariate model (Observer, factor with 3 levels) to the amakihi data, all is well for the analysis with published truncation distance of 82.5

```
library(Distance)
data(amakihi)
amakihi$OBs <- relevel(amakihi$OBs, ref="TKP")
amak.hr.obs.82.5 <- ds(amakihi, transect="point", key="hr", formula=~OBs, 
                                convert.units = conv, truncation=82.5)
summary(amak.hr.obs.82.5$ddf)
```
Things continue fine, decrementing trunction by 1m, until reaching w=75
```
amak.hr.obs.75 <- ds(amakihi, transect="point", key="hr", formula=~OBs, 
                              convert.units = conv,  truncation=75)
plot(amak.hr.obs.75, pdf=TRUE)
amak.hr.obs.75$ddf$ds$niter
amak.hr.obs.75$ddf$ds$converge
```
No complaints are issued, but apparently only 3 iterations were attempted before finishing.

![image](https://user-images.githubusercontent.com/330744/81503968-90ebf800-92de-11ea-9dda-f7e6102ec6de.png)

**Comment by dill** [comment]
This should be fixed by changes to starting value code in [3b3708d](https://github.com/DistanceDevelopment/mrds/commit/3b3708df53dbcc3cbf463c1cf12c0c91ae3810b9).

**Comment by dill** [comment]
(That is, in `mrds` rather than in `Distance`.)

**Comment by erex** [comment]
thanks Dave, .9002 of `mrds` does give reasonable results when fitting to the amakihi data with considerable truncation
![image](https://user-images.githubusercontent.com/330744/88454403-4f8fd100-ce67-11ea-968a-edd408075cd6.png)
I'll have a look for another hazard rate point transect data set, but consider this resolved for now.
