### ISSUE TITLE
Flatfile with observer column

### ISSUE THREAD

**Issue by meriops** [DistanceDevelopment/Distance#63]
This is more a comment than a real issue...
I was teaching today and we realized that the number of observations displayed in the summary of the (simple) model output (using `Distance::ds()`) didn't match the number of observations in the data set. The data frame was formatted to the `flatfile` format, but with extra variables to be used as covariates. It took me a while to figure out that  one of these extra columns was a factor named `observer`, so `mrds::ddf()` was actually subsetting the data to the first observer only (as hinted to in the doc for `ddf()`).
This is easy to avoid once you know about it, but for casual users or students using mostly `ds()`, it might be worth a warning or a precision in the documentation for `ds()` or for `flatfile`...

**Comment by dill** [comment]
Thanks for this! I just looked into this (in fact one bug previously, #62) and I've made some changes to check for these reserved columns. This will be in the next CRAN release in the next few months.
