### ISSUE TITLE
Multipliers with uncertainty for `bootdht` (or equivalent new function)

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#69]
See discussion at #64, from that

```
Perhaps we can have both multipliers and sample_fraction as in dht2 but for now when the $se element of the multipliers is not zero we throw an error?
```

**Comment by lenthomas** [comment]
Perhaps we could increase the ambition and include uncertainty for 1.0.2?  The issue is then that we will need to have a way that the user can specify which distribution to sample from as this part of the bootstrap will necessarily need to be parametric.

**Comment by erex** [comment]
Email from former workshop participant (2019)

> I hope things have been well in St. Andrews since the last time we met at the distance workshop in 2019! I have read with interest your analysis example entitled "Detecting density estimate differences" on the distance sampling website. I have what I think is a simple question (famous last words). Would the bootstrapping methods you use in this example analysis also be applicable to testing the differences in two density estimates in which the detection functions and encounter rates used for density estimation are identical, but each estimate uses a different method for calculating a multiplier? I think the answer is yes, but I would like to check with you to make sure I am not overlooking an unforeseen issue. Of course, the estimates would not be independent and thus I think would be similar to testing differences between the densities in two strata that both use a pooled detection function and share a covariate. The reason I ask is I am currently trying to compare two different deer density estimates from the same pellet sampling data that each used a different method for calculating pellet decay rate. So, essentially, the only thing that will differ between my two deer density estimates is the multiplier.

**Comment by lenthomas** [comment]
After discussions with @dill, we aim to have this enhanced functionality in release 1.0.4.  Full specification and interface will be discussed after release 1.0.3 is out.

**Comment by dill** [comment]
Closing this issue as it's covered by #100.
