### ISSUE TITLE
`bootdht` fails with amakihi because area=0

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#70]
Perhaps an error trap is needed for this case

```
data(amakihi)
conv <- convert_units("meter", NULL, "hectare")
surv <- ds(amakihi, transect="point", key="hr", 
+            formula=~Region.Label, convert.units=conv, truncation = 82.5)
am.surv.boot <- bootdht(surv, flatfile=amakihi, nboot=5)
Performing 5 bootstraps
Warning message:
In dht(model, region.table, sample.table, obs.table, options = list(group = dht.group,  :
  Point transect encounter rate variance can only use estimators P2 or P3, switching to P3.
summary(am.surv.boot)
Bootstrap results

Boostraps          : 5 
Successes          : 5 
Failures           : 0 

data frame with 0 columns and 0 rows

am.surv.boot
named list()
attr(,"class")
[1] "dht_bootstrap"
attr(,"row.names")
integer(0)
attr(,"nboot")
[1] 5
attr(,"nbootfail")
[1] 0
```
A most brutal error because no error is generated; bootstrap can take hours to complete but at the end, analyst has no results.

the default result harvesting function `bootdht_Nhat_summarize` finds nothing to harvest when abundance is not present in the situation of area=0

**Comment by dill** [comment]
Agree, will look into this.

**Comment by dill** [comment]
9329cee should address this. The error now returned is

```
No Area in flatfile, densities will be returned and the default summary function records only abundances. You need to write your own summary_fun.
```

Let me know if that needs clarifying.

**Comment by erex** [comment]
looks good

**Comment by lenthomas** [comment]
Would it be more appropriate to make this a warning rather than an error?  Just a thought.

**Comment by dill** [comment]
I don't think there is a use case for this. To be specific, this is when the default summary function is used (`bootdht_Nhat_summarize`) and the `Area` column is all `0` or `NULL`. In this case it definitely will not produce output as the element `ests$individuals$N` never exists.

**Comment by lenthomas** [comment]
I'm afraid I don't know what a "use case" is, so I couldn't quite parse your response!

**Comment by dill** [comment]
er, ~"I don't think anyone will ever want to run a bootstrap but not get any results"

**Comment by lenthomas** [comment]
Ah, okay, yes.

(You might want to fix a very small typo in the documentation to bootdht - I think number 3 and 4 in this list should be combined: 
![Annotation 2020-07-25 165806](https://user-images.githubusercontent.com/129519/88460969-099f3100-ce98-11ea-8c5f-c3e04176f9b8.jpg)
)
