### ISSUE TITLE
Improve bootstrap progress bar user interface

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#71]
Given the potential issues with the bootstrap, I wonder if we can improve the user experience a bit by giving better user feedback.

One option is something like [`progress`](https://github.com/r-lib/progress), which would allow us to give an ETA and % of failed replicates, letting the user know how things are going during the bootstrap.

Thoughts?

**Comment by dill** [comment]
(If we're worried about dependencies, this could be a `Suggests` and we can detect if it's installed at runtime, defaulting to `utils::txtProgressBar` which we currently have.)

**Comment by erex** [comment]
no strong opinion.  I mess up my knitr documents when I forget to accommodate progress bars.

**Comment by lenthomas** [comment]
I think a progress bar is a good idea! I'm not fussed whether it is fancy or text based, but if its easy then the dual method you propose sounds good @dill; an option to turn it off for cases such as knitr would be good.

**Comment by dill** [comment]
As of 983e0c3 `Distance` can use [`progress`](https://github.com/r-lib/progress) (if it's installed, the package is only suggested, so will not be installed by default with `Distance`) to generate a progress bar with an ETA estimated during the bootstrap. Also a "none" option to show no output  (per @erex's issue above).

e.g. (using the model fitted in `?bootdht`):

```r
> bootout <- bootdht(mod1, flatfile=minke, summary_fun=Nhat_summarize, nboot=5)
Performing 5 bootstraps
  |======================================================================| 100%
> bootout <- bootdht(mod1, flatfile=minke, summary_fun=Nhat_summarize, nboot=5,
+                    progress_bar="none")
Performing 5 bootstraps

> bootout <- bootdht(mod1, flatfile=minke, summary_fun=Nhat_summarize, nboot=5,
+                    progress_bar="progress")
Performing 5 bootstraps
   [=============================================================] 100% eta:  0s
