### ISSUE TITLE
Metadata for `dht`/`dht` estimates//default ER var estimation

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#76]
(This is a joint `mrds` and `Distance` issue.)

Currently when using point transect data, if you specify an ER estimator that isn't P2/P3 a warning is thrown, letting the user know that `dht` is defaulting to P3. This stops users specifying other estimators and assuming they worked.
This can be annoying though.

Two solutions to two related issues:

1. check if see if the encounter rate variance estimator has been specified by the user (via `missing()`) and only throw the error if it has (this is a bit complicated for `Distance` calling `dht` but can be done).
2. I have been thinking for `dht2` (but could be done for `dht` too) we should have some metadata saved to let the user know which options were called with the function and therefore what the estimators were etc. This is currently stored in `$call` for `dht2` objects but I think it would be nice in the summary to say "ER variance estimator: R2 using N/L" or "ER variance estimator: P3 using n/L" etc. This would make me less nervous about suppressing output.

**Comment by lenthomas** [comment]
I agree with both these suggested solutions.

**Comment by dill** [comment]
I've added this extra info in `mrds::dht` and `Distance::dht2` now.

Keen to hear if folks have thoughts about the wording that gets printed.

Currently we have:

```
Abundance and density estimates from distance sampling
Variance       : R2, N/L  
```

in `dht` where the second line will display the ER estimator, `N/L`/`n/L`/`binomial`.

`dht2` will do the same but the "Abundance and density" part will change based on the `report=` argument to `print`.

**Comment by erex** [comment]
No problem with the printed wording.  Is it worth echoing the other arguments associated with `dht2`, such as `multipliers`, `sample_fraction`?

**Comment by dill** [comment]
What were you thinking for `multipliers` and `sample_fraction`? The number if it's a single number and a "were used" or somesuch if it was a more complicated situation?

**Comment by erex** [comment]
That sounds reasonable.  Whenever additional features are employed, would be useful for the output to note that they were used: multipliers: TRUE/FALSE perhaps, and their numerical values if easy.

**Comment by dill** [comment]
I tried with numerical values, but things looked a little messy. I settled on:

```
Abundance estimates from distance sampling
Stratification : geographical 
Variance       : P2, n/L 
Multipliers    : creation 
Sample faction : 0.5 


Summary statistics:
 .Label   Area CoveredArea Effort  n  k    ER se.ER cv.ER
  Total 168000     82.4932  36.47 40 92 1.097 0.303 0.276

Abundance estimates:
 .Label Estimate       se    cv  LCI   UCI     df
  Total    13654 5263.071 0.385 6112 30500 13.058

Component percentages of variance:
 .Label Detection    ER Multipliers
  Total      21.7 51.38       26.92
```

and when there are no multipliers and sample faction is default:

```
Abundance estimates from distance sampling
Stratification : geographical 
Variance       : P2, n/L 
Multipliers    : none 
Sample faction : 1 


Summary statistics:
 .Label   Area CoveredArea Effort  n  k    ER se.ER cv.ER
  Total 168000    164.9864  36.47 40 92 1.097 0.303 0.276

Abundance estimates:
 .Label Estimate       se   cv   LCI    UCI      df
  Total   170673 56240.07 0.33 90428 322124 129.994

Component percentages of variance:
 .Label Detection    ER
  Total     29.69 70.31
```

(Based on the cue count example.)
