### ISSUE TITLE
argument names in `ds` and `dht2`

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#78]
Seems inconsistent for `ds` to have an argument named `convert.units`, while `dht2` has an argument named `convert_units` (which happens to be named the same as the function `convert_units`)

**Comment by lenthomas** [comment]
I wonder if this should be part of a wider discussion on coding conventions for whether and when to use an underscore vs a dot for naming objects, functions and arguments.  I recall we had this discussion recently at a DistDev group meeting, but don't recall the conclusion.  I'll start up a DistDev issue on this for internal discussion, and then we can loop back here once resolved.

**Comment by lenthomas** [comment]
This is currently being discussed in DistanceDevelopment/distance-dev#49 and we'll update here once resolved.
