### ISSUE TITLE
AIC.dsmodel takes ... but does not pass it and it is undocumented

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/Distance#8]
AIC.dsmodel <- function(object, ..., k=2)

the ... arguments are not documented (this is generating a warning when the package is checked)
as these arguments are not passed on to any other function I wasn't sure what they were supposed to be

**Comment by dill** [comment]
Just pushed a change that should fix this.

**Comment by LHMarshall** [comment]
Yep fixed
