### ISSUE TITLE
Output of ESW/EDR with associated uncertainty and CI

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/Distance#80]
The goal here is to add to the ds summary output of effective strip width/detection radius with associated uncertainty and 95% confidence interval.  This is a parallel to the enhancement planned in mrds https://github.com/DistanceDevelopment/mrds/issues/36

**Comment by dill** [comment]
Closing as this will be automatically done when DistanceDevelopment/mrds#36 is closed.
