### ISSUE TITLE
Point-specific sampling fraction

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#89]
Question from the [list](https://groups.google.com/u/1/g/distance-sampling/c/nuC0JerV8f4/m/qz9rcLYJBQAJ) 24May21 requested point-specific sampling fraction, as view angle of observer changes for each point.

Might that be a possible enhancement to `dht2`?

**Comment by dill** [comment]
In principle yes. The thing that gets tricky here is specifying it in a way that is easy for the user and easy for us to check. If this goes into `dht2` it should also go into `bootdht` at the same time.

I quickly thought about how to implement this and it probably requires more thought than that...

- `sample_fraction` becomes a vector. Okay but then it either needs to be the same length as flatfile, which is fine but we then need to check consistency between the rows when transects have >1 detection. Fine but lots of redundancy.
- New column in flatfile/`transects`, fine but then what do we do about the `sample_fraction` argument? Remove this redundancy?
- `sample_fraction` becomes a `data.frame`, one column for the `Sample.Label` and one for the fraction. Okay, more complicated but fits within the existing argument structure.

In the meantime, the user could modify `Effort` accordingly to get the same effect?

**Comment by lenthomas** [comment]
Great stuff.  Yes, I agree it can be done in the meantime with effort, but would be great to have as sample fraction as more straightforward for users.  Variable field of view seems to happen a bit in camera trap applications, for example.  Regarding interface, I support the data.frame approach - so it could be a scalar or a data frame.  Mind you that new column in flatfile is also appealing as it's straightforward.  Thoughts @erex ?

**Comment by erex** [comment]
Clever to think of multiple solutions to the problem.  From the users' perspective, conceptually smoothest to place in the data.  Building a vector or data frame could create a greater chance to screw up.  I understand that defeats the idea of a `sample_fraction` argument.

**Comment by lenthomas** [comment]
I guess we could have two options - sample fraction argument for a scalar and flatfile column if more nuance is needed.  Could just issue a warning or error if both used in same dataset?

**Comment by dill** [comment]
Having just dealt with this for multipliers at #92, I suggest we go with single number OR a `data.frame`. In the multiplier case I do a `merge` onto the H-T table, so the user can specify any column in the data (e.g., `Sample.Label` or a stratification variable). That way the user only needs to specify data at the granularity they have and ordering doesn't matter.

Examples:

```
sample_fraction_sample <- data.frame(Sample.Label = c(1,2,3,4,...),
                                     sample_fraction = c(0.2, 0.3, 0.6, 0.9, ...))

sample_fraction_strat <- data.frame(Region.Label = c("North", "South"),
                                    sample_fraction = c(0.2, 0.9)) 
```

Thoughts?

**Comment by lenthomas** [comment]
Fine by me - so long as it's clear in the documentation then users should be able to figure it out.
