### ISSUE TITLE
test_package("Distance") not working

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/Distance#9]
I have added tests in test_ds.R to check the modification I have made in the file test_ds.R but test_package is not running:

test_package("Distance")
Error: No tests found for Distance

**Comment by dill** [comment]
I use devtools::test(). That seems to work on my machine.

Let me know if that's not working for you.

**Comment by LHMarshall** [comment]
That works... although still slightly puzzled as to why test_package fails

**Comment by dill** [comment]
I think this was so our tests don't run on CRAN, avoiding grumpyness and 
taking time on their servers, so they don't show up as "test" only 
within devtools framework.
