### ISSUE TITLE
Stratum-specific multipliers with `dht2`

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/Distance#92]
[Question from the list](https://groups.google.com/g/distance-sampling/c/xV-0Pwl93Ww) regarding use of multipliers for each stratum.  Regardless that multipliers are specified as data frames (allowing multiple rows), `dht2` throws an error at [line 500](https://github.com/DistanceDevelopment/Distance/blob/45e3747ba274624d5e630d92ded3d1a030b90593/R/dht2.R#L500) if a data frame with multiple rows is passed in as multiplier.

Seems the check at [line 470](https://github.com/DistanceDevelopment/Distance/blob/45e3747ba274624d5e630d92ded3d1a030b90593/R/dht2.R#L470) does not catch multi-row data frames.

A one row data frame `bigmult` is defined on [line 475](https://github.com/DistanceDevelopment/Distance/blob/45e3747ba274624d5e630d92ded3d1a030b90593/R/dht2.R#L475) is added to a multiple row data frame on line 500.

```
Error in `$<-.data.frame`(`*tmp*`, rate_CV, value = c(0.0291493158834027,  : 
  replacement has 2 rows, data has 1
```

MRE with our minke friends:

```
library(Distance)
data("minke")
easy <- ds(data=minke, key="hr", truncation=1.5)
mult <- list(creation = data.frame(rate=c(0.41, 0.47), 
                                SE=c(0.07, 0.06)))
res_dens <- dht2(easy, flatfile=minke, 
                 strat_formula = ~Region.Label, 
                 stratification="geographical",
                 multipliers = mult)
```

**Comment by dill** [comment]
This should be fixed in 3a9fedf. I think this was a feature we talked about but never got around to dealing with properly. I've updated the documentation too to try to make it obvious how to use this but welcome suggestions.

**Comment by erex** [comment]
thanks for the change as well as describing in documentation.  Shall I ask Pablo to give it a whirl?

**Comment by dill** [comment]
please do!

**Comment by lenthomas** [comment]
Hmm... might be something I'm doing wrong, but I get an error with @erex code from above:
```
> library(Distance)
Loading required package: mrds
This is mrds 2.2.4.9004
Built: R 4.0.2; ; 2021-06-15 13:55:49 UTC; windows

Attaching package: ‘Distance’

The following object is masked from ‘package:mrds’:

    create.bins
> data("minke")
> easy <- ds(data=minke, key="hr", truncation=1.5)
Starting AIC adjustment term selection.
Fitting hazard-rate key function
Key only model: not constraining for monotonicity.
AIC= 48.637
Fitting hazard-rate key function with cosine(2) adjustments
AIC= 50.386

Hazard-rate key function selected.
> mult <- list(creation = data.frame(rate=c(0.41, 0.47), 
+                                    SE=c(0.07, 0.06)))
> res_dens <- dht2(easy, flatfile=minke, 
+                  strat_formula = ~Region.Label, 
+                  stratification="geographical",
+                  multipliers = mult)
Error in matrix(dat_row$weight, nrow = 1) %*% vcov : 
  non-conformable arguments
```

**Comment by dill** [comment]
Thanks @lenthomas. I'm getting that too now, but wasn't when I closed the issue so I'll double check that...

**Comment by dill** [comment]
Ah I see what happened here. Sorry I should have pasted in my code, as the code here doesn't work because there are two multipliers but no information in how to apply them (additional labels to merge them on). I've added better checking of the multipliers, so an error is raised before we get to the error you pasted.
