### ISSUE TITLE
Use `skip_on_cran()` for tests where necessary

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#93]
Per #91, add `skip_on_cran()` where numerical tests are used that won't work cross-platform, or where computations will be time-consuming.

**Comment by LHMarshall** [comment]
@dill (@alex-konovalov ) so skip on CRAN means that CRAN will not run them but will they be run on the CI checks? But they will be run by devtools::test() locally? 

I was starting to name files different things so I could run additional checks locally... so my test-that.R file contains a filter test_check("dssd", filter = "check_.*") so not all the tests get run on CRAN and CI testing it skips the long running and tests that require set.seeds.

**Comment by dill** [comment]
yeah there's an environment variable `NOT_CRAN` set by `devtools` and if it's set then the tests run, see [here](https://testthat.r-lib.org/reference/skip.html).  A bit annoying to do it for each test, your system mighty be less frustrating to setup. I guess I'll find out...

**Comment by alex-konovalov** [comment]
@LHMarshall yes, there are even more ways to skip
- `skip_on_covr()` skips when covr is running (using the R_COVR env var).
- `skip_on_ci()` skips on continuous integration systems like GitHub Actions, travis, and appveyor.
- `skip_on_os()` skips on the specified operating system(s) ("windows", "mac", "linux", or "solaris").

but yes, it's tedious. I like the filtered idea, but it is possible to have 3 tiers, maybe by adding some subdirectories, for options like
- runs on CI and CRAN
- runs on CI but not on CRAN
- runs neither on CI, nor on CRAN, only could be run manually?
