### ISSUE TITLE
QAIC for model selection

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/Distance#99]
See [here](https://examples.distancesampling.org/Distance-cameratraps/camera-distill.html#model-selection-adjustments-from-overdispersion) for code implementing the QAIC of:

Howe, E. J., Buckland, S. T., Després-Einspenner, M.-L., & Kühl, H. S. (2019). Model selection with overdispersed distance sampling data. Methods in Ecology and Evolution, 10(1), 38–47. 10.1111/2041-210X.13082

**Comment by dill** [comment]
First version of this is now in the `ctds-2021` branch (cb012d4). 

Checks to see that the key is the same for all models and tries to stick with the output format for the `AIC` S3 method.

e.g.:

```r
# remotes::install_github("DistanceDevelopment/Distance", "ctds-2021")
library(Distance)
data(minke)
model1 <- ds(minke, truncation=4, adjustment=NULL)
model2 <- ds(minke, truncation=4, adjustment="cos", order=2)
model4 <- ds(minke, truncation=4, adjustment="cos", order=c(2, 4))
model6 <- ds(minke, truncation=4, adjustment="cos", order=c(2, 4, 6))
# calculate QAIC
QAIC(model1, model2, model4, model6)
```

which gives:

```
       df     QAIC
model1  1 749.9088
model2  2 753.4320
model4  3 755.3890
model6  4 756.6858
```

Documentation is pasted directly from the vignette, so could certainly be improved.

**Comment by dill** [comment]
Quick question for @erex and @lenthomas: should the function generate a warning/message/stop if only one detection function is supplied?

**Comment by erex** [comment]
I would suggest if only a single model is passed in then there is no model selection to perform.  I suppose the right thing to do would be to pass a message to that effect and stop.

**Comment by dill** [comment]
Okay, added the following error in the case where only one model is supplied: "Only 1 model specified, no model selection can be performed".

**Comment by lenthomas** [comment]
Is it also possible to pass in a "c" value manually to QAIC (as an optional argument)?  In that case, it would make sense for the default to be NULL and the error to be triggered, but if it is some positive value then it would be fine to ask to calculate QAIC on just one fit.   Also, does the QAIC as implemented return (or somehow make it possible to obtain) the c value it calculates and uses?

**Comment by dill** [comment]
That's possible. Would `c` or `chat` (or something else) be preferable?

**Comment by erex** [comment]
Len: are you thinking of the "manual" value of c-hat to deal with the second overdispersion method in Howe's 2019 paper (c_2 in the notation of that paper)?

**Comment by lenthomas** [comment]
Partly, and partly as a general expansion of the method, so it's more generally applicable in future - the user is then free to decide for themselves how they calculate the chat.  

Regarding what to call the argument, the QAIC function in MuMIn uses chat, so we could use the same?  

(I also note it has a k argument as well, as does AIC, so it's probably worth exposing that also, with default 2.)  

BTW, in the help to QAIC in MuMIn, it says "In calculation of QAIC, the number of model parameters is increased by 1 to account for estimating the overdispersion parameter."  I don't think we do that, nor is it mentioned in Howe's paper?

**Comment by dill** [comment]
wrt number of model pars/overdispersion, @lenthomas are you referring to what Eric H says on p. 40 of his MEE paper: "Burnham and Anderson (2001, 2002) clarified that ĉ should be included as one of the K parameters." If so I think this is included in @erex's original code, see e.g. https://github.com/DistanceDevelopment/Distance/commit/4b67b76723bca3858deb54ca01aed60b2c597c5e#diff-f44837a452a2e156f1c5c54ae873b3a86956480cad4b644f77e625079b6d0c2aR89

**Comment by erex** [comment]
email from Len Thomas 02Jul21

> We were wondering whether you plan to mention/teach also c2, and whether we should incldue that as well?

email from Eric Howe on 14Jul21

> I think we should include chat_2 as well as chat_1, if only to be consistent with the 2019 article, but also to allow researchers to explore differences. Chat_2 is simpler with simpler expectations (should underfit) relative to chat_1.

**Comment by dill** [comment]
From Howe et al 2019:

*The number of distance observations recorded per independent encounter between an animal and an observer provides an alternative measure of the magnitude of overdispersion (ĉ2). ĉ2 will often be calculable from the raw data, and will be the same for all models in the candidate set. In CT surveys of solitary animals, ĉ2 would be the mean number of distance observations recorded during a single pass by an animal in front of a CT. In surveys of social animals employing human observers, ĉ2 would be the mean number of detected animals per detected group, and in CT surveys of social animals ĉ2
the mean number of distance observations recorded during an encounter between a group of animals and a CT.*

This sounds to me like the kind of thing that needs to get estimated externally and passed in? I don't think we can auto-calculate this from the data we have in a normal detection function. This would be fine to pass to the current `chat` argument, so I don't think this requires a code change but rather just an addition to the documentation?

**Comment by dill** [comment]
I've added some documentation to explain this based on the excerpt above. If one or both of you could give that a look-over (as people who actually know about this kind of analysis) and give suggestions then I think we can close this issue?

**Comment by erex** [comment]
Discrepancies in QAIC (method 1) computations between Howe etal paper and Distance (DistanceDevelopment/Distance@cc5fba2)

I wonder if the difference in $c_1$ is because of Hermite adjustments used?

Table S5 of Howe et al (2018) and results using:


| key fn   | $c_1$ | Distance |
| -------- | -----:| --------:|
| hazard   | 12.39 |     12.4 | 
| uniform  | 26.58 |     26.6 |
| halfnorm | ==34.90== |     ==22.2== |


| hn      | AIC(EH)  | AIC(ER)  |
| ------- | -------- | -------- |
| HP(4,6) | ==25014.18== | ==24946.05== |
| HP(4)   | ==25025.90== | ==24944.60==  |
| HP      | 25081.60 | 25081.61 |

QAIC comparison for Hazard

|     |  df | Distance |   Howe |
|:--- | ---:| --------:| ------:|
| hr0 |   2 | 2009.813 | 2013.6 |
| hr1 |   3 | 2009.813 | 2015.6 |
| hr2 |   4 | 2009.813 | 2017.6 |
|     |     |          |        |

QAIC comparison for uniform cosine

|      |  df | Distance |   Howe |
|:---- | ---:| --------:| ------:|
| uni1 |   1 | 942.6180 | 944.39 |
| uni2 |   2 | 942.4803 | 946.25 | 


QAIC comparison for Half normal

|     |  df | Distance |   Howe |
|:--- | ---:| --------:| ------:|
| hn0 |   1 | 1130.719 | 722.61 |
| hn1 |   2 | 1124.462 | 722.96 |
| hn2 |   3 | 1124.438 | 724.57 |

I think this is close to what EJH reported by email.  Have not tried his fix to the `qaic` function.

**Comment by dill** [comment]
Thanks for these @erex, are these using the "peak" data? I've patched locally per the e-mail with Eric H, but still have some discrepencies, so I'll try to track those down before I push...

**Comment by erex** [comment]
correct, using the "peak" data set, shipped in the Distance package.  Haven't messed with the "daytime" data set used in Practical 5.  My plan is not to go through model selection in Practical 5 (daytime) given everything else that's jammed into Practical 5 (activity package, bootstrap).

**Comment by dill** [comment]
Thanks, I'll look into this and report back.

**Comment by dill** [comment]
Sorry one further question: to be clear, the results in the second table are AIC not QAIC?

**Comment by erex** [comment]
yes, I was hunting for where differences emerged; first looked at $c_1$, then went to AIC, then finally to QAIC.  EJH's AIC values were in the supplemental material from his paper (attached).  I think he did his model fitting in DistWin, but I'm not certain.
[mee313082-sup-0001-supinfo(1).docx](https://github.com/DistanceDevelopment/Distance/files/6863890/mee313082-sup-0001-supinfo.1.docx)

**Comment by dill** [comment]
Understood, thanks. Didn't want to start tracking down bugs in comparisons in the wrong numbers.

**Comment by dill** [comment]
Not finished thinking about this, but here is my working so far, in case it's interesting.

Script for generation [here](https://gist.github.com/dill/a39806a3dd6115922893db877d687648).

Fitting the models in Howe et al, I get the following table, where "_Distance" indicates the values from `Distance`.

|Model  |      AIC| AIC_Distance|   QAIC1| QAIC_Distance|    c1| c1_Distance|
|:------|--------:|------------:|-------:|-------------:|-----:|-----------:|
|Hr     | 24877.61|     24877.60| 2013.55|     2086.4635| 12.39|    11.95580|
|Hrcos1 | 24879.61|     24879.60| 2015.55|     2088.4635| 12.39|    11.95580|
|Hrcos2 | 24881.60|     24881.15| 2017.55|     2090.4255| 12.39|    11.95580|
|Uncos1 | 24997.46|     24997.45|  944.39|      944.6180| 26.58|    26.57343|
|Uncos2 | 24995.81|     24995.79|  946.25|      946.4803| 26.58|    26.57343|
|Hn     | 25081.60|     25081.61|  722.61|      894.8562| 34.90|    28.15225|
|HnHp1  | 25025.90|     24949.47|  722.96|      895.9493| 34.90|    28.15225|
|HnHp2  | 25014.18|     24946.05|  724.57|      893.8988| 34.90|    28.15225|

We see agreement for uniform models, differences for hr and hn. The hn differences are likely due to re-writes of the Hermite polynomial code in `mrds`, so the likelihoods are different (and better) than those in the paper. For the hr though this is more tricky as the differences in likelihood (hence AIC) are small.

For info looking at those hr models we see:

<img width="1420" alt="Screenshot 2021-07-23 at 09 14 13" src="https://user-images.githubusercontent.com/1953/126754937-ba83503f-b6e4-4f70-974b-0ad83fdcb157.png">

Where the hr+cos(2) model has a cosine coefficient ~1e-8, so the fits look very similar. The hr+cos(2,4) model is clearly wacky here. Comparing this to the models Eric H provided via e-mail (presumably fitted in an earlier version of `Distance`), which look like this:

<img width="1210" alt="Screenshot 2021-07-23 at 09 26 55" src="https://user-images.githubusercontent.com/1953/126756224-f7e05453-414b-40a5-8f97-4e2677a74bd9.png">

where both fits have cosine coefficients ~1e-8, leading to almost identical plots.

The likelihood for the "bad" hn+cos(2,4) model is -12436.19 and for the "good" model is -12436.8. It looks like the optimizer stopped just a little bit too soon (so likely the convergence criterion is a little too tight).

I can try to look into this but I think that the issue here is in the detection function fitting rather than the `QAIC` function.

**Comment by erex** [comment]
As I understand the current QAIC function, it performs what is described in this passage:
> in step one, we obtain  ̂c_1 from the most highly parameterised model within each key function (rather than from the most highly parameterised model overall), use those values of  ̂c_1 to calculate QAIC for all models with the same key function, and use QAIC to identify the best-supported model within each key function. In this step, the same value of  ̂c_1 is used to calculate QAIC for all models with the same key function, but different values of  ̂c_1 are used to calculate QAIC for different key functions.

I'm unsure how to compute the χ2/df calculation for the second step of model selection using Method 1 of Howe et al (2019) described here:
> In step two, we compare values of the χ2 GOF statistic divided by its df across QAIC-selected models (one from each key function), and choose the model with the smallest value for estimation.

In other words, recompute χ2/df for the "winning" model from each key function.  This is the same value as computed in step one, IF the selected model is the most complex, which for the peak duiker data set, it is not.  What is needed is to access the `chat` function for a single model.  I had thought I could cheat and call QAIC with a single model as argument and pluck out the `chat` attribute, but that's not the case
```
> bob <- QAIC(hn1)
Error in QAIC(hn1) : 
  Only 1 model specified, no model selection can be performed
```

Also cannot access the [`chat`](https://github.com/DistanceDevelopment/Distance/blob/ac1d964c0cbdf1a4d3d8e19e04f701be797d1c59/R/QAIC.R#L98) function that is inside `QAIC` because it is in the `QAIC` environment.

**Comment by erex** [comment]
At present, the "best" QAIC models from step 1 (duiker peak data on my computer) are:

Table: QAIC values for uniform key models.

|     | df|     QAIC|
|:----|--:|--------:|
|uni1 |  1| 944.6180|
|uni2 |  2| 946.4803|

Table: QAIC values for hazard rate key models.

|    | df|     QAIC|
|:---|--:|--------:|
|hr0 |  2| 2110.675|
|hr1 |  3| 2112.675|
|hr2 |  4| 2114.572|

Table: QAIC values for half normal key models.

|    | df|     QAIC|
|:---|--:|--------:|
|hn0 |  1| 1132.719|
|hn1 |  2| 1128.462|
|hn2 |  3| 1130.438|

Namely, `uni1`, `hr0` (same as original paper) and `hn1` rather than `hn0`.

Using these models to pass into step 2, computing chi2/df for each, the result of "best model for inference" is unchanged from the manuscript:

|lab  |     chat|
|:----|--------:|
|uni1 | 23.21992|
|hr0  |  8.25894|
|hn1  | 18.59755|

These chi2/df values are identical to values in Table S5 of the manuscript, except the half-normal value is smaller, but not smaller than the value of the metric for `hr0`

**Comment by dill** [comment]
Thanks for this extra detail and explanation, I had not appreciated the second stage issue fully.

Wondering what would be the best output for users of the function here. I can see that we probably want to keep hold of the c1 value used for the 1st stage selection, but also want to unambiguously present the chi^2/df value for the top model too.

Currently the c1 value used for the model selection (or the `chat` supplied) is stored at `attr(*, "chat")`. Suggest we include the  chi^2/df value in `attr(*, "chat_best")` and present that in the ouput when printing the resutl of `QAIC`?

**Comment by erex** [comment]
Good question what would be the best form of output.

Because there are 2 steps, the way I did it for the vignette was to have human intervention (pick smallest QAIC for each key function).  Then a second call handing in the "winners" from the first round, simply computing the chi2/df for each and spitting out a data frame of the winners, sorted by chi2/df.

No real need for human intervention, the function could be smart enough to sort by QAIC within each key function family, and pass models with lowest QAIC (by key function) off for further chi2/df analysis.

How much hassle take in all models of all key families, dive into the model object to discover the key for each model, do pass1, then pass2?  In the end, spit out a data frame with rows containing all models, column of chat (pass1), QAIC, then chat(pass2) with NA for chat(pass2) for models that weren't winners of pass1.  Sounds messy, don't know I have a better idea.

**Comment by lenthomas** [comment]
I might be off-base here, but:

In general, we do not recommend automated model selection between key functions.  It's not supported in Distance for Windows (it is in mcds.exe but I didn't port through to the interface) and I think it's not supported in ds().  Better to fit each key function separately, check each is reasonable and then think about selecting among them.  So, if there's an additional step involved in this for camera trap models that's fine by me, so long as we have clear instructions on how to do it.  Just a thought.

**Comment by erex** [comment]
I don't have an opinion about automated/non-automated.  Could be a function for pass1, then a different function for pass2.  But the idea of the second pass is to rank models across key functions.  Guess you're arguing for sending back the ordering, which is consistent with my suggestion.  

I understand the principle of not being a slave to AIC, but as described in Howe et al. (2018), there isn't ambiguity regarding model selection (passage from p.40)
![image](https://user-images.githubusercontent.com/330744/126819522-17cadbf8-a1a5-4048-ba5a-8f2c33796818.png)


To be a pedant, a user sent me this DistWin analysis configuration earlier this week:
![image](https://user-images.githubusercontent.com/330744/126818983-3c90d8e9-3023-4710-8696-5ba9a3dcd253.png)
the result of which is to perform within key and between key model selection without user intervention, reporting back the estimates produced by a single model across all models fitted.

**Comment by lenthomas** [comment]
Good point re DistWin @erex  - I'd totally forgotten that I built in the ability to run multiple key functions even if not encouraged.  One legit use of this is to incorporate model uncertainty into a nonparametric bootstrap.

**Comment by dill** [comment]
Okay, so following from the idea of 2 functions how does the following workflow look:

```r
>  data(minke)
>  # fit models
>  mod_hn_1 <- ds(minke, truncation=4, adjustment=NULL)
Fitting half-normal key function
Key only model: not constraining for monotonicity.
AIC= 64.819
>  mod_hn_2 <- ds(minke, truncation=4, adjustment="cos", order=2)
Fitting half-normal key function with cosine(2) adjustments
AIC= 66.779
>  mod_hn_4 <- ds(minke, truncation=4, adjustment="cos", order=c(2, 4))
Fitting half-normal key function with cosine(2,4) adjustments
AIC= 68.776
>  mod_hr_1 <- ds(minke, truncation=4, key="hr", adjustment=NULL)
Fitting hazard-rate key function
Key only model: not constraining for monotonicity.
AIC= 69.729
>  mod_hr_2 <- ds(minke, truncation=4, key="hr", adjustment="cos", order=2)
Fitting hazard-rate key function with cosine(2) adjustments
 mod_hr_4 <- ds(minke, truncation=4, key="hr", adjustment="cos", order=c(2, 4))
AIC= 71.728
>  mod_hr_4 <- ds(minke, truncation=4, key="hr", adjustment="cos", order=c(2, 4)
)
Fitting hazard-rate key function with cosine(2,4) adjustments
 # calculate QAIC (stage 1)
 QAIC(mod_hn_1, mod_hn_2, mod_hn_4)
 QAIC(mod_hr_1, mod_hr_2, mod_hr_4)
AIC= 70.859
>  # calculate QAIC (stage 1)
>  QAIC(mod_hn_1, mod_hn_2, mod_hn_4)
         df     QAIC
mod_hn_1  1 690.7001
mod_hn_2  2 692.2623
mod_hn_4  3 694.2228
>  QAIC(mod_hr_1, mod_hr_2, mod_hr_4)
         df     QAIC
mod_hr_1  2 297.6753
mod_hr_2  3 299.6717
mod_hr_4  4 288.9427
>  # select between best half-normal and hazard-rate models
>  chi2_select(mod_hn_1, mod_hr_4)
           criteria
mod_hn_1 0.06846872
mod_hr_4 0.22534859
```

**Comment by erex** [comment]
I'm content with a two-step, two-function approach; as I employed in the vignette.  What do you think of `pass2` or `chat2` or some such as the name of the second function?

BTW, Howe et al. (2019) uses Steve's Montrave robin data as a second example of the model selection procedure.  Perhaps that could serve as the basis of tests rather than the minkes.  I'll sort out the robins data for experiments with the revised model selection code.

**Comment by erex** [comment]
maximum distance in minke data is 1.94, so `truncation=4` is unusual

**Comment by dill** [comment]
Must have been half-asleep when setting the truncation, but happy for the wrens to replace the minkes.

`chat2` seems fine to me, I'll write-up these changes and let you know once they're done.

**Comment by erex** [comment]
actually, scratch the `chat2` idea (that's the notation EJH uses for the Method 2 approach).  Guess something more like you originally had `chi2_df` might be less ambiguous
![image](https://user-images.githubusercontent.com/330744/126965511-9d912cda-0bb6-4aa9-8a81-536da72c9d36.png)

**Comment by erex** [comment]
Portion of Fig. 2 of Howe et al. (2019) showing winter wren density estimates from models selected by Buckland and by QAIC1 procedure
![image](https://user-images.githubusercontent.com/330744/126971414-918a5981-3b54-41b2-9292-ebb39194dbaf.png)

No difference in model choice resulting from QAIC procedure

```
data("wren_cuecount")
w3.hr0 <- ds(wren_cuecount, transect="point", key="hr", adjustment=NULL, truncation=92.5)
w3.hr1 <- ds(wren_cuecount, transect="point", key="hr", adjustment="cos", order=2, truncation=92.5)
w3.hr2 <- ds(wren_cuecount, transect="point", key="hr", adjustment="cos", order=c(2, 4), truncation=92.5)


w3.u1 <- ds(wren_cuecount, transect="point", key="unif", adjustment="cos", order=1, truncation=92.5)
w3.u2 <- ds(wren_cuecount, transect="point", key="unif", adjustment="cos", 
            order=c(1,2), monotonicity="none",  truncation=92.5)
w3.u3 <- ds(wren_cuecount, transect="point", key="unif", adjustment="cos", 
            order=c(1,2,3), monotonicity="none", truncation=92.5)

w3.hn0 <- ds(wren_cuecount, transect="point", key="hn", adjustment=NULL, truncation=92.5)
w3.hn1 <- ds(wren_cuecount, transect="point", key="hn", adjustment="herm",
             order=2, truncation=92.5)
w3.hn2 <- ds(wren_cuecount, transect="point", key="hn", adjustment="herm",
             order=c(4,6), truncation=92.5)

QAIC(w3.hr0, w3.hr1, w3.hr2)  # no adjustments smallest
QAIC(w3.u1, w3.u2, w3.u3)     # 2 adjustment terms (by 0.07)
QAIC(w3.hn0, w3.hn1, w3.hn2)  # no adjustments smallest

hrgof <- gof_ds(w3.hr0, chisq = TRUE)$chisquare$chi1
hrpass2 <- hrgof$chisq / hrgof$df
unigof <- gof_ds(w3.u2, chisq=TRUE)$chisq$chi1
unipass2 <- unigof$chisq / unigof$df
hngof <- gof_ds(w3.hn0, chisq=TRUE)$chisq$chi1
hnpass2 <- hngof$chisq / hngof$df
result <- data.frame(name=c("hr0", "uni2", "hn0"), pass2=c(hrpass2, unipass2, hnpass2))
knitr::kable(result)
|name |    pass2|
|:----|--------:|
|hr0  | 25.86191|
|uni2 | 27.08342|
|hn0  | 27.05415|

**Comment by dill** [comment]
Thanks for that, I've switched the example now and added the `chi2_select` function.

**Comment by erex** [comment]
thx Dave.  Formatting of help for `QAIC` looks odd in RStudio
![image](https://user-images.githubusercontent.com/330744/126977433-34065f03-1ed4-4107-a500-6cf486b72df0.png)

something about `deqn`?

also not seeing a help entry for `chi2_select`

**Comment by dill** [comment]
I've updated the documentation so that `QAIC` and `chi2_select` are documented in the same place, with further instructions on their use (it seems logical to have their manual page be the same, since you'd naturally use them together). Also fixed the `deqn` issue. Let me know what you think of those instructions and if there's any additional information that might be useful.

**Comment by erex** [comment]
agree about location of man pages.  reference to `chat1 and 2` in documentation looks fine.  I think documentation is sufficient, you've provided the citation to the paper if folks want more details.

**Comment by dill** [comment]
Great, in which case I will close this issue unless there's anything else missing?

**Comment by erex** [comment]
In a workshop planning meeting at 1400 today, EJH was asking about the newly invented `QAIC` and `chi2_select` functions.  I suggest we keep the issue open for 24 hours so that he can have a look at them and their documentation; then close.
